# Generated by Django 5.0 on 2026-01-05 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "in_app_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable in-app notifications"
                    ),
                ),
                (
                    "email_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable email notifications"
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable push notifications (future feature)",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-type notification preferences (e.g., {'milestone_achieved': true, 'job_match': false})",
                    ),
                ),
                (
                    "digest_frequency",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="weekly",
                        help_text="Frequency for notification digest emails",
                        max_length=50,
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True,
                        help_text="Start of quiet hours (24-hour format, e.g., 22:00)",
                        null=True,
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True,
                        help_text="End of quiet hours (24-hour format, e.g., 08:00)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User who owns these preferences",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("milestone_achieved", "Milestone Achieved"),
                            ("course_completed", "Course Completed"),
                            ("job_match", "Job Match Found"),
                            ("roadmap_generated", "Roadmap Generated"),
                            ("assessment_complete", "Assessment Complete"),
                            ("roadmap_updated", "Roadmap Updated"),
                            ("new_course_added", "New Course Added"),
                            ("skill_recommendation", "Skill Recommendation"),
                            ("system_announcement", "System Announcement"),
                            ("achievement_unlocked", "Achievement Unlocked"),
                        ],
                        db_index=True,
                        help_text="Type of notification",
                        max_length=100,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=255),
                ),
                ("message", models.TextField(help_text="Notification message content")),
                (
                    "related_entity_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Type of related entity (roadmap, course, job, milestone, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "related_entity_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="ID of related entity",
                        null=True,
                    ),
                ),
                (
                    "action_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to redirect user when clicking notification",
                        max_length=1000,
                    ),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True,
                        help_text="Text for action button/link (e.g., 'View Roadmap', 'See Details')",
                        max_length=100,
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when notification was read",
                        null=True,
                    ),
                ),
                (
                    "delivery_status",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                        ],
                        default="sent",
                        help_text="Delivery status of notification",
                        max_length=50,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        help_text="Notification priority level",
                        max_length=50,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context data for notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User receiving this notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user", "-created_at"], name="idx_notif_user"),
                    models.Index(fields=["notification_type"], name="idx_notif_type"),
                    models.Index(fields=["user", "is_read"], name="idx_notif_unread"),
                    models.Index(fields=["-created_at"], name="idx_notif_created"),
                    models.Index(fields=["priority"], name="idx_notif_priority"),
                    models.Index(
                        fields=["related_entity_type", "related_entity_id"],
                        name="idx_notif_entity",
                    ),
                ],
            },
        ),
    ]
