# Generated by Django 5.2.8 on 2025-11-16 02:14

import apps.users.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "auth0_id",
                    models.CharField(
                        db_index=True,
                        help_text="Auth0 user identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="User email address",
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                code="invalid_email",
                                message="Enter a valid email address.",
                                regex="^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$",
                            )
                        ],
                    ),
                ),
                (
                    "email_verified",
                    models.BooleanField(
                        default=False, help_text="Whether email has been verified"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        help_text="Unique username",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "full_name",
                    models.CharField(help_text="User full name", max_length=255),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        help_text="Date of birth (must be 13+ years old)",
                        validators=[apps.users.models.validate_age],
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Phone number", max_length=20, null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether user account is active"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, help_text="Whether user can access admin site"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(
                        default=False, help_text="Whether user has premium subscription"
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deleted", "Deleted"),
                        ],
                        default="active",
                        help_text="Account status",
                        max_length=50,
                    ),
                ),
                (
                    "onboarding_completed",
                    models.BooleanField(
                        default=False, help_text="Whether user has completed onboarding"
                    ),
                ),
                (
                    "onboarding_step",
                    models.IntegerField(
                        default=0,
                        help_text="Current onboarding step (0-indexed)",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("ar", "Arabic")],
                        default="en",
                        help_text="Preferred language",
                        max_length=10,
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Africa/Cairo", help_text="User timezone", max_length=50
                    ),
                ),
                (
                    "last_login_at",
                    models.DateTimeField(
                        blank=True, help_text="Last login timestamp", null=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Skill name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly skill identifier",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Skill description", null=True
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("soft", "Soft Skills"),
                            ("business", "Business"),
                            ("design", "Design"),
                            ("data", "Data & Analytics"),
                            ("marketing", "Marketing"),
                            ("other", "Other"),
                        ],
                        help_text="Skill category",
                        max_length=100,
                    ),
                ),
                (
                    "skill_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        help_text="Typical skill level for this skill",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether skill is active in the system"
                    ),
                ),
                (
                    "popularity_score",
                    models.IntegerField(
                        default=0,
                        help_text="Popularity score for ranking",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "parent_skill",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent skill if this is a sub-skill",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_skills",
                        to="users.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill",
                "verbose_name_plural": "Skills",
                "db_table": "skills",
                "ordering": ["-popularity_score", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications"
                    ),
                ),
                (
                    "weekly_digest",
                    models.BooleanField(
                        default=True, help_text="Receive weekly digest emails"
                    ),
                ),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("connections", "Connections Only"),
                        ],
                        default="public",
                        help_text="Profile visibility",
                        max_length=50,
                    ),
                ),
                (
                    "show_progress",
                    models.BooleanField(
                        default=True, help_text="Show learning progress publicly"
                    ),
                ),
                (
                    "preferred_learning_style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("visual", "Visual"),
                            ("auditory", "Auditory"),
                            ("reading", "Reading/Writing"),
                            ("kinesthetic", "Kinesthetic"),
                        ],
                        help_text="Preferred learning style",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "daily_learning_goal_minutes",
                    models.IntegerField(
                        default=30,
                        help_text="Daily learning goal in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "reminder_time",
                    models.TimeField(
                        blank=True,
                        help_text="Preferred time for learning reminders",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skill_type",
                    models.CharField(
                        choices=[("hard", "Hard Skill"), ("soft", "Soft Skill")],
                        help_text="Skill type",
                        max_length=50,
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        help_text="User proficiency level",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Years of experience with this skill",
                        max_digits=4,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(99.99),
                        ],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user_input", "User Input"),
                            ("assessment", "Assessment"),
                            ("verified", "Verified"),
                        ],
                        default="user_input",
                        help_text="Source of skill data",
                        max_length=50,
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Whether skill is verified"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, help_text="When skill was verified", null=True
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="users.skill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who has this skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Who verified this skill",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Skill",
                "verbose_name_plural": "User Skills",
                "db_table": "user_skills",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="idx_users_email"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["auth0_id"], name="idx_users_auth0_id"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="idx_users_username"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_login_at"], name="idx_users_last_login"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["name"], name="idx_skills_name"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["slug"], name="idx_skills_slug"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["category"], name="idx_skills_category"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(fields=["parent_skill"], name="idx_skills_parent"),
        ),
        migrations.AddIndex(
            model_name="skill",
            index=models.Index(
                fields=["-popularity_score"], name="idx_skills_popularity"
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(fields=["user"], name="idx_user_skills_user"),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(fields=["skill"], name="idx_user_skills_skill"),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(fields=["skill_type"], name="idx_user_skills_type"),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(
                fields=["proficiency_level"], name="idx_user_skills_proficiency"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userskill",
            unique_together={("user", "skill")},
        ),
    ]
