"""One-shot, ordered reset of the graduation-demo data.

Replaces the fragile multi-command sequence in GRADUATION_DEMO_RUNBOOK.md with a
single idempotent command that runs every step in the *correct* order and prints
a per-step ✓/✗ summary, so a skipped or mis-ordered step can no longer silently
produce zero course matches or an ungrounded advisor.

Ordering matters: the demo roadmap is generated by ``seed_graduation_demo``,
which matches real courses onto its milestones. That matcher reads the published
course catalog (``seed_courses``) and its embedding index
(``rebuild_course_index``), so both must run *before* the demo seed — the reverse
of the old runbook order.

The advisory RAG corpus (``career_knowledge``, ~64k chunks built by
``python -m src.rag.build_vector_db``) is a build-once, persists-on-disk artifact
and is therefore *verified*, never rebuilt, here.

Usage::

    python manage.py demo_reset                 # full ordered reset
    python manage.py demo_reset --jobs 30
    python manage.py demo_reset --skip-ai-smoke # offline rehearsal
"""

from __future__ import annotations

import time
from io import StringIO

from django.core.management import call_command
from django.core.management.base import BaseCommand


# Below this count the advisory corpus is considered "not built" — the KB-only
# seed yields ~33 chunks, the full corpus ~64k. Anything in between is broken.
_CORPUS_MIN_DOCS = 1000


class Command(BaseCommand):
    help = "Reset all graduation-demo data in the correct order with a ✓/✗ summary."

    def add_arguments(self, parser):
        parser.add_argument(
            "--jobs",
            type=int,
            default=24,
            help="Number of demo jobs to seed (default: 24).",
        )
        parser.add_argument(
            "--migrate",
            action="store_true",
            help="Run database migrations first (for a fresh setup).",
        )
        parser.add_argument(
            "--skip-ai-smoke",
            action="store_true",
            help="Skip the live Gemini round-trip (offline rehearsal).",
        )
        parser.add_argument(
            "--skip-corpus-check",
            action="store_true",
            help="Skip the advisory corpus verification.",
        )

    def handle(self, *args, **options):
        jobs = options["jobs"]
        results: list[tuple[str, bool, str]] = []

        steps: list[tuple[str, callable]] = []
        if options["migrate"]:
            steps.append(("migrate", lambda: self._call("migrate")))

        steps.extend(
            [
                # Catalog + index BEFORE the demo seed so roadmap generation can
                # match real courses onto the returning user's milestones.
                ("seed_courses --clear", lambda: self._call("seed_courses", clear=True)),
                ("rebuild_course_index", lambda: self._call("rebuild_course_index")),
                ("seed_graduation_demo --reset", lambda: self._call("seed_graduation_demo", reset=True)),
                (f"seed_jobs --clear --count {jobs}", lambda: self._call("seed_jobs", clear=True, count=jobs)),
                (f"extract_job_skills --limit {jobs} --replace", lambda: self._call("extract_job_skills", limit=jobs, replace=True)),
            ]
        )
        if not options["skip_corpus_check"]:
            steps.append(("verify advisory corpus", self._verify_corpus))
        if not options["skip_ai_smoke"]:
            steps.append(("ai_smoke (Gemini round-trip)", self._ai_smoke))

        self.stdout.write(self.style.MIGRATE_HEADING("\nGraduation demo reset\n"))
        for label, fn in steps:
            start = time.time()
            try:
                detail = fn() or ""
                ok = True
            except Exception as error:  # keep going; report at the end
                ok = False
                detail = f"{type(error).__name__}: {error}"
            elapsed = time.time() - start
            mark = self.style.SUCCESS("✓") if ok else self.style.ERROR("✗")
            self.stdout.write(f"  {mark} {label}  ({elapsed:.1f}s)" + (f"  {detail}" if detail else ""))
            results.append((label, ok, detail))

        self._summary(results)

    # -- step helpers ---------------------------------------------------------

    def _call(self, command: str, **kwargs) -> str:
        """Run a management command quietly; surface only failures."""
        buffer = StringIO()
        call_command(command, stdout=buffer, stderr=buffer, **kwargs)
        return ""

    def _verify_corpus(self) -> str:
        """Check the advisory corpus is built (does NOT rebuild it)."""
        try:
            from rag import vector_store
        except Exception as error:  # rag package not importable
            raise RuntimeError(
                f"cannot import rag package ({error}); advisory will use fallbacks"
            )
        count = vector_store.get_document_count()
        if count < _CORPUS_MIN_DOCS:
            raise RuntimeError(
                f"only {count} docs in 'career_knowledge' (expected ~64k). "
                f"Build it once: cd ai-models && python -m src.rag.build_vector_db"
            )
        return f"{count} docs"

    def _ai_smoke(self) -> str:
        from apps.core.ai_settings import GEMINI_API_KEYS

        if not GEMINI_API_KEYS:
            return "skipped (no GEMINI_API_KEY — offline fallbacks apply)"
        self._call("ai_smoke")
        return "Gemini reachable"

    # -- reporting ------------------------------------------------------------

    def _summary(self, results: list[tuple[str, bool, str]]) -> None:
        failed = [r for r in results if not r[1]]
        self.stdout.write("")
        if not failed:
            self.stdout.write(self.style.SUCCESS("Demo reset complete — all steps passed."))
            self.stdout.write("Demo accounts: demo.new@sha8alny.local / demo.progress@sha8alny.local (DemoPass123!)")
            return
        self.stdout.write(self.style.ERROR(f"Demo reset finished with {len(failed)} failed step(s):"))
        for label, _ok, detail in failed:
            self.stdout.write(self.style.ERROR(f"  ✗ {label}: {detail}"))
