# Generated by Django 5.0 on 2026-01-05 23:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("roadmaps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneAchievement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "achieved_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When milestone was achieved"
                    ),
                ),
                (
                    "time_to_complete_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days taken to complete this milestone",
                        null=True,
                    ),
                ),
                (
                    "badge_awarded",
                    models.BooleanField(
                        default=False,
                        help_text="Whether a badge was awarded for this achievement",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of badge awarded (e.g., 'Speed Demon', 'Perfectionist')",
                        max_length=100,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        help_text="Milestone that was achieved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="roadmaps.roadmapmilestone",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who achieved the milestone",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_achievements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Achievement",
                "verbose_name_plural": "Milestone Achievements",
                "ordering": ["-achieved_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeLog",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When learning session started"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(help_text="When learning session ended"),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        help_text="Duration in minutes (1-1440, max 24 hours)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("course", "Course Learning"),
                            ("practice", "Practice/Exercises"),
                            ("reading", "Reading Documentation"),
                            ("project", "Project Work"),
                        ],
                        help_text="Type of learning activity",
                        max_length=50,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Course associated with this time log (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="courses.course",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        blank=True,
                        help_text="Roadmap associated with this time log (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to="roadmaps.roadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged the time",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Log",
                "verbose_name_plural": "Time Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="UserProgress",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Overall completion percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "phases_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of phases completed"
                    ),
                ),
                (
                    "milestones_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of milestones completed"
                    ),
                ),
                (
                    "courses_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of courses completed"
                    ),
                ),
                (
                    "total_learning_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Total hours spent learning on this roadmap",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_streak_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Current consecutive days streak"
                    ),
                ),
                (
                    "longest_streak_days",
                    models.PositiveIntegerField(
                        default=0, help_text="Longest streak achieved"
                    ),
                ),
                (
                    "last_activity_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of last learning activity",
                        null=True,
                    ),
                ),
                (
                    "average_hours_per_week",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average hours per week spent on this roadmap",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "on_track",
                    models.BooleanField(
                        default=True,
                        help_text="Whether user is on track to complete roadmap on time",
                    ),
                ),
                (
                    "current_milestone",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current milestone user is working on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_users",
                        to="roadmaps.roadmapmilestone",
                    ),
                ),
                (
                    "current_phase",
                    models.ForeignKey(
                        blank=True,
                        help_text="Current phase user is working on",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_users",
                        to="roadmaps.roadmapphase",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        help_text="Roadmap being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="roadmaps.roadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose progress is being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Progress",
                "verbose_name_plural": "User Progress Records",
                "ordering": ["-last_activity_date", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CourseCompletion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(help_text="When user started the course"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(help_text="When user completed the course"),
                ),
                (
                    "time_spent_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total hours spent on this course",
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=100.0,
                        help_text="Completion percentage (default 100% for full completion)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="User rating (1-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "user_review",
                    models.TextField(
                        blank=True, help_text="User's written review of the course"
                    ),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether user would recommend this course",
                        null=True,
                    ),
                ),
                (
                    "has_certificate",
                    models.BooleanField(
                        default=False, help_text="Whether user earned a certificate"
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to certificate (if available)",
                        max_length=1000,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course that was completed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="courses.course",
                    ),
                ),
                (
                    "roadmap_course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated roadmap course (if part of roadmap)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completions",
                        to="roadmaps.roadmapcourse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who completed the course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_completions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Completion",
                "verbose_name_plural": "Course Completions",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-completed_at"], name="idx_compl_user_date"
                    ),
                    models.Index(
                        fields=["course", "-completed_at"], name="idx_compl_course_date"
                    ),
                    models.Index(
                        fields=["roadmap_course"], name="idx_compl_roadmap_course"
                    ),
                    models.Index(fields=["-user_rating"], name="idx_compl_rating"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="coursecompletion",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "course"),
                name="unique_user_course_completion",
            ),
        ),
        migrations.AddIndex(
            model_name="milestoneachievement",
            index=models.Index(
                fields=["user", "-achieved_at"], name="idx_achv_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="milestoneachievement",
            index=models.Index(
                fields=["milestone", "-achieved_at"], name="idx_achv_milestone_date"
            ),
        ),
        migrations.AddIndex(
            model_name="milestoneachievement",
            index=models.Index(fields=["badge_awarded"], name="idx_achv_badge"),
        ),
        migrations.AddConstraint(
            model_name="milestoneachievement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "milestone"),
                name="unique_user_milestone_achievement",
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "-started_at"], name="idx_tlog_user_started"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["course", "-started_at"], name="idx_tlog_course_started"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["roadmap", "-started_at"], name="idx_tlog_roadmap_started"
            ),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(fields=["activity_type"], name="idx_tlog_activity_type"),
        ),
        migrations.AddIndex(
            model_name="timelog",
            index=models.Index(
                fields=["user", "started_at"], name="idx_tlog_user_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="timelog",
            constraint=models.CheckConstraint(
                condition=models.Q(("ended_at__gt", models.F("started_at"))),
                name="chk_timelog_chronology",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["user", "-last_activity_date"], name="idx_prog_user_activity"
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(
                fields=["roadmap", "-overall_completion_percentage"],
                name="idx_prog_roadmap_completion",
            ),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(fields=["-current_streak_days"], name="idx_prog_streak"),
        ),
        migrations.AddIndex(
            model_name="userprogress",
            index=models.Index(fields=["on_track"], name="idx_prog_on_track"),
        ),
        migrations.AddConstraint(
            model_name="userprogress",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "roadmap"),
                name="unique_user_roadmap_progress",
            ),
        ),
    ]
