# Generated by Django 5.2.8 on 2025-11-17 05:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assessment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assessment_type",
                    models.CharField(
                        choices=[
                            ("skills", "Skills Assessment"),
                            ("career_interests", "Career Interests"),
                            ("personality", "Personality Assessment"),
                            ("learning_style", "Learning Style"),
                            ("comprehensive", "Comprehensive Assessment"),
                        ],
                        db_index=True,
                        help_text="Type of assessment",
                        max_length=100,
                    ),
                ),
                (
                    "questions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Assessment questions in structured format",
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="User responses to assessment questions",
                    ),
                ),
                (
                    "ai_processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        help_text="AI processing status for analysis",
                        max_length=50,
                    ),
                ),
                (
                    "ai_processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When AI processing completed", null=True
                    ),
                ),
                (
                    "ai_processing_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message if AI processing failed",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("abandoned", "Abandoned"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Assessment completion status",
                        max_length=50,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user started the assessment",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When user completed the assessment",
                        null=True,
                    ),
                ),
                (
                    "total_questions",
                    models.IntegerField(
                        default=0,
                        help_text="Total number of questions",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "answered_questions",
                    models.IntegerField(
                        default=0,
                        help_text="Number of answered questions",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "time_spent_seconds",
                    models.IntegerField(
                        default=0,
                        help_text="Total time spent on assessment in seconds",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User taking the assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment",
                "verbose_name_plural": "Assessments",
                "db_table": "assessments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentResult",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Overall assessment score (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "skill_scores",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed skill scores by category",
                    ),
                ),
                (
                    "strengths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Identified strengths from assessment",
                    ),
                ),
                (
                    "areas_for_improvement",
                    models.JSONField(
                        blank=True, default=list, help_text="Areas needing improvement"
                    ),
                ),
                (
                    "recommended_careers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="AI-recommended career paths",
                    ),
                ),
                (
                    "recommended_learning_paths",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Recommended skills to learn",
                    ),
                ),
                (
                    "ai_insights",
                    models.TextField(
                        blank=True, help_text="Natural language AI-generated insights"
                    ),
                ),
                (
                    "ai_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI confidence in analysis (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "llm_model_used",
                    models.CharField(
                        blank=True,
                        help_text="LLM model used for analysis (e.g., gpt-4, claude-3)",
                        max_length=100,
                    ),
                ),
                (
                    "llm_prompt_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of prompt tokens used",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "llm_completion_tokens",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of completion tokens used",
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Time taken for AI processing in seconds",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Assessment algorithm version",
                        max_length=50,
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="Whether user has shared this result"
                    ),
                ),
                (
                    "assessment",
                    models.OneToOneField(
                        help_text="Assessment this result belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="assessments.assessment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assessment Result",
                "verbose_name_plural": "Assessment Results",
                "db_table": "assessment_results",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["user"], name="idx_assessments_user"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["assessment_type"], name="idx_assessments_type"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(fields=["status"], name="idx_assessments_status"),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["ai_processing_status"], name="idx_assessments_ai_status"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["-completed_at"], name="idx_assessments_completed"
            ),
        ),
        migrations.AddIndex(
            model_name="assessment",
            index=models.Index(
                fields=["user", "assessment_type"], name="idx_assessments_user_type"
            ),
        ),
        migrations.AddIndex(
            model_name="assessmentresult",
            index=models.Index(fields=["assessment"], name="idx_results_assessment"),
        ),
        migrations.AddIndex(
            model_name="assessmentresult",
            index=models.Index(fields=["overall_score"], name="idx_results_score"),
        ),
        migrations.AddIndex(
            model_name="assessmentresult",
            index=models.Index(fields=["-created_at"], name="idx_results_created"),
        ),
    ]
