# Generated by Django 5.0 on 2026-04-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="target_career",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Selected target career path for this assessment",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
