# Generated by Django 5.0 on 2025-12-26 21:52

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPlatform",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Platform name (e.g., 'Wuzzuf', 'LinkedIn', 'Bayt')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        help_text="Platform's main website URL", max_length=500
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Platform logo URL", max_length=500
                    ),
                ),
                (
                    "has_api",
                    models.BooleanField(
                        default=False, help_text="Whether platform provides an API"
                    ),
                ),
                (
                    "api_endpoint",
                    models.URLField(
                        blank=True,
                        help_text="API base URL if available",
                        max_length=500,
                    ),
                ),
                (
                    "requires_scraping",
                    models.BooleanField(
                        default=True, help_text="Whether web scraping is needed"
                    ),
                ),
                (
                    "scraping_enabled",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether scraping is currently active",
                    ),
                ),
                (
                    "target_countries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of countries this platform covers (e.g., ['Egypt', 'Saudi Arabia'])",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether platform is actively being used",
                    ),
                ),
                (
                    "last_scraped_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful scrape",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Platform",
                "verbose_name_plural": "Job Platforms",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="idx_job_platform_name"),
                    models.Index(fields=["slug"], name="idx_job_platform_slug"),
                    models.Index(fields=["is_active"], name="idx_job_platform_active"),
                    models.Index(
                        fields=["scraping_enabled"], name="idx_job_platform_scraping"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Platform's unique job ID", max_length=255
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        help_text="Direct link to job posting on platform",
                        max_length=1000,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Job title", max_length=500
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        db_index=True,
                        help_text="Company offering the job",
                        max_length=255,
                    ),
                ),
                (
                    "company_logo_url",
                    models.URLField(
                        blank=True, help_text="Company logo URL", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Full job description"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, help_text="Job requirements and qualifications"
                    ),
                ),
                (
                    "responsibilities",
                    models.TextField(
                        blank=True, help_text="Job responsibilities and duties"
                    ),
                ),
                (
                    "location_city",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="City location",
                        max_length=100,
                    ),
                ),
                (
                    "location_country",
                    models.CharField(
                        db_index=True,
                        default="Egypt",
                        help_text="Country location",
                        max_length=100,
                    ),
                ),
                (
                    "is_remote",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Whether job is remote"
                    ),
                ),
                (
                    "remote_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fully_remote", "Fully Remote"),
                            ("hybrid", "Hybrid"),
                            ("on_site", "On-Site"),
                        ],
                        help_text="Remote work arrangement",
                        max_length=50,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        db_index=True,
                        help_text="Employment type",
                        max_length=50,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior Level"),
                            ("lead", "Lead/Manager"),
                            ("executive", "Executive"),
                        ],
                        db_index=True,
                        help_text="Required experience level",
                        max_length=50,
                    ),
                ),
                (
                    "experience_years_min",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum years of experience required",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "experience_years_max",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum years of experience required",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum salary",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum salary",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="EGP",
                        help_text="Salary currency code (ISO 4217)",
                        max_length=10,
                    ),
                ),
                (
                    "salary_period",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("hourly", "Hourly"),
                        ],
                        help_text="Salary payment period",
                        max_length=50,
                    ),
                ),
                (
                    "salary_disclosed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether salary information is publicly disclosed",
                    ),
                ),
                (
                    "application_deadline",
                    models.DateField(
                        blank=True, help_text="Application deadline date", null=True
                    ),
                ),
                (
                    "posted_date",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        help_text="Date job was posted",
                        null=True,
                    ),
                ),
                (
                    "platform_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional platform-specific fields",
                    ),
                ),
                (
                    "last_fetched_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time job data was fetched"
                    ),
                ),
                (
                    "cache_expires_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="When cached job data expires (24hr TTL)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether job posting is still active",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform this job was scraped from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="jobs.jobplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-posted_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether skill is required or just nice-to-have",
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        help_text="Required proficiency level",
                        max_length=50,
                    ),
                ),
                (
                    "years_required",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Years of experience required with this skill",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Job requiring this skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="jobs.job",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Required skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_skills",
                        to="users.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Skill",
                "verbose_name_plural": "Job Skills",
                "ordering": ["-is_required", "skill__name"],
            },
        ),
        migrations.CreateModel(
            name="MarketInsight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("job_demand", "Job Demand Analysis"),
                            ("salary_trend", "Salary Trend Analysis"),
                            ("skill_trend", "Skill Trend Analysis"),
                            ("company_hiring", "Company Hiring Trends"),
                            ("location_trend", "Location Trends"),
                        ],
                        db_index=True,
                        help_text="Type of market insight",
                        max_length=50,
                    ),
                ),
                (
                    "career_field",
                    models.CharField(
                        db_index=True,
                        help_text="Career field (e.g., 'Backend Development', 'Data Science')",
                        max_length=100,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        default="Egypt",
                        help_text="Country for this insight",
                        max_length=100,
                    ),
                ),
                (
                    "data_period_start",
                    models.DateField(help_text="Start date of data period"),
                ),
                (
                    "data_period_end",
                    models.DateField(help_text="End date of data period"),
                ),
                (
                    "insights_data",
                    models.JSONField(
                        default=dict, help_text="Aggregated insights and analytics data"
                    ),
                ),
                (
                    "total_jobs_analyzed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of jobs analyzed for this insight"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this insight was generated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Market Insight",
                "verbose_name_plural": "Market Insights",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(fields=["insight_type"], name="idx_insight_type"),
                    models.Index(fields=["career_field"], name="idx_insight_field"),
                    models.Index(fields=["country"], name="idx_insight_country"),
                    models.Index(fields=["generated_at"], name="idx_insight_generated"),
                    models.Index(
                        fields=["insight_type", "career_field", "country"],
                        name="idx_insight_composite",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SkillDemand",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        db_index=True,
                        default="Egypt",
                        help_text="Country for this demand data",
                        max_length=100,
                    ),
                ),
                (
                    "month",
                    models.DateField(
                        db_index=True, help_text="Month of data (first day of month)"
                    ),
                ),
                (
                    "demand_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of jobs requiring this skill in this month",
                    ),
                ),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("rising", "Rising"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                        ],
                        db_index=True,
                        help_text="Trend direction compared to previous month",
                        max_length=50,
                    ),
                ),
                (
                    "trend_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage change from previous month",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("-100.00")
                            ),
                            django.core.validators.MaxValueValidator(
                                Decimal("1000.00")
                            ),
                        ],
                    ),
                ),
                (
                    "average_salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average minimum salary for jobs requiring this skill",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "average_salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average maximum salary for jobs requiring this skill",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "top_job_titles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of most common job titles requiring this skill",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill being tracked",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_data",
                        to="users.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Skill Demand",
                "verbose_name_plural": "Skill Demand Data",
                "ordering": ["-month", "-demand_count"],
            },
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["platform", "external_id"], name="idx_job_platform_ext"
            ),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["title"], name="idx_job_title"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["company_name"], name="idx_job_company"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location_city"], name="idx_job_city"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["location_country"], name="idx_job_country"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["job_type"], name="idx_job_type"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["experience_level"], name="idx_job_exp_level"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["is_remote"], name="idx_job_remote"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["is_active"], name="idx_job_active"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["cache_expires_at"], name="idx_job_cache_exp"),
        ),
        migrations.AddIndex(
            model_name="job",
            index=models.Index(fields=["posted_date"], name="idx_job_posted"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("platform", "external_id"),
                name="unique_job_platform_external_id",
            ),
        ),
        migrations.AddIndex(
            model_name="jobskill",
            index=models.Index(fields=["job"], name="idx_jobskill_job"),
        ),
        migrations.AddIndex(
            model_name="jobskill",
            index=models.Index(fields=["skill"], name="idx_jobskill_skill"),
        ),
        migrations.AddIndex(
            model_name="jobskill",
            index=models.Index(fields=["is_required"], name="idx_jobskill_required"),
        ),
        migrations.AddIndex(
            model_name="skilldemand",
            index=models.Index(fields=["skill"], name="idx_skilldemand_skill"),
        ),
        migrations.AddIndex(
            model_name="skilldemand",
            index=models.Index(fields=["country"], name="idx_skilldemand_country"),
        ),
        migrations.AddIndex(
            model_name="skilldemand",
            index=models.Index(fields=["month"], name="idx_skilldemand_month"),
        ),
        migrations.AddIndex(
            model_name="skilldemand",
            index=models.Index(
                fields=["trend_direction"], name="idx_skilldemand_trend"
            ),
        ),
        migrations.AddIndex(
            model_name="skilldemand",
            index=models.Index(
                fields=["skill", "country", "month"], name="idx_skilldemand_composite"
            ),
        ),
        migrations.AddConstraint(
            model_name="skilldemand",
            constraint=models.UniqueConstraint(
                fields=("skill", "country", "month"), name="unique_skill_country_month"
            ),
        ),
    ]
