# Generated by Django 5.0.14 on 2026-01-17 03:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional user notes about this job"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        help_text="Job that was saved",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="jobs.job",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who saved this job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Saved Job",
                "verbose_name_plural": "Saved Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="idx_savedjob_user"),
                    models.Index(fields=["job"], name="idx_savedjob_job"),
                    models.Index(fields=["created_at"], name="idx_savedjob_created"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="savedjob",
            constraint=models.UniqueConstraint(
                fields=("user", "job"), name="unique_user_job"
            ),
        ),
    ]
