# Generated by Django 5.0.14 on 2026-01-17 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_savedjob_savedjob_unique_user_job"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="savedjob",
            name="unique_user_job",
        ),
        migrations.AddConstraint(
            model_name="savedjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("user", "job"),
                name="unique_user_job_active",
            ),
        ),
    ]
