# Generated by Django 5.0 on 2025-11-29 07:04

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assessments", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Roadmap title (personalized for the user)",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated description tailored to user's needs",
                    ),
                ),
                (
                    "target_career",
                    models.CharField(
                        help_text="User's target job title/career goal", max_length=255
                    ),
                ),
                (
                    "current_level",
                    models.CharField(
                        blank=True,
                        help_text="User's current skill level/position",
                        max_length=255,
                    ),
                ),
                (
                    "target_level",
                    models.CharField(
                        help_text="Target skill level/position to achieve",
                        max_length=255,
                    ),
                ),
                (
                    "estimated_duration_weeks",
                    models.PositiveIntegerField(
                        help_text="AI-estimated duration based on user's pace and commitment"
                    ),
                ),
                (
                    "weekly_hours_commitment",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Expected weekly hours user will dedicate (1-168)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(168),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        help_text="Current roadmap status",
                        max_length=20,
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Overall completion percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user started following this roadmap",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user completed this roadmap",
                        null=True,
                    ),
                ),
                (
                    "ai_processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Status of AI roadmap generation",
                        max_length=20,
                    ),
                ),
                (
                    "ai_processed_at",
                    models.DateTimeField(
                        blank=True, help_text="When AI processing completed", null=True
                    ),
                ),
                (
                    "ai_processing_error",
                    models.TextField(
                        blank=True, help_text="Error message if AI processing failed"
                    ),
                ),
                (
                    "llm_model_used",
                    models.CharField(
                        blank=True,
                        help_text="LLM model used for generation (e.g., 'gpt-4', 'claude-3')",
                        max_length=100,
                    ),
                ),
                (
                    "llm_prompt_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of prompt tokens used"
                    ),
                ),
                (
                    "llm_completion_tokens",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of completion tokens used"
                    ),
                ),
                (
                    "processing_time_seconds",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Time taken for AI processing in seconds",
                        max_digits=10,
                    ),
                ),
                (
                    "ai_insights",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI-generated insights about user's learning path",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional roadmap data (preferences, adjustments, etc.)",
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Assessment result that triggered this roadmap generation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roadmaps",
                        to="assessments.assessmentresult",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this roadmap",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap",
                "verbose_name_plural": "Roadmaps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapPhase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Phase title (e.g., 'Backend Fundamentals')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of this phase"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Sequential order of this phase in the roadmap"
                    ),
                ),
                (
                    "estimated_duration_weeks",
                    models.PositiveIntegerField(
                        help_text="Estimated duration for this phase in weeks"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        help_text="Current phase status",
                        max_length=20,
                    ),
                ),
                (
                    "completion_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Phase completion percentage (0-100)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When user started this phase", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user completed this phase",
                        null=True,
                    ),
                ),
                (
                    "objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Learning objectives for this phase: [objective1, objective2, ...]",
                    ),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        help_text="Roadmap this phase belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="roadmaps.roadmap",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Phase",
                "verbose_name_plural": "Roadmap Phases",
                "ordering": ["roadmap", "order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapMilestone",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Milestone title/description", max_length=500
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Detailed description of what to achieve"
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("course", "Course/Tutorial"),
                            ("project", "Project/Practice"),
                            ("reading", "Reading/Documentation"),
                            ("practice", "Coding Practice"),
                            ("assessment", "Assessment/Quiz"),
                        ],
                        default="course",
                        help_text="Type of milestone activity",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="Sequential order within the phase"
                    ),
                ),
                (
                    "estimated_duration_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated time to complete this milestone (hours)",
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        help_text="Current milestone status",
                        max_length=20,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this milestone is required or optional",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of skill UUIDs learned: [uuid1, uuid2, ...]",
                    ),
                ),
                (
                    "resources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Additional resources: [{title, url, type}, ...]",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user completed this milestone",
                        null=True,
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        help_text="Phase this milestone belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="roadmaps.roadmapphase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Milestone",
                "verbose_name_plural": "Roadmap Milestones",
                "ordering": ["phase", "order"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Template name (e.g., 'Backend Developer Roadmap')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Detailed description of this career path"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief one-liner description",
                        max_length=500,
                    ),
                ),
                (
                    "target_career",
                    models.CharField(
                        db_index=True,
                        help_text="Target job title (e.g., 'Backend Developer', 'Data Scientist')",
                        max_length=255,
                    ),
                ),
                (
                    "career_level",
                    models.CharField(
                        choices=[
                            ("entry_level", "Entry Level"),
                            ("mid_level", "Mid Level"),
                            ("senior_level", "Senior Level"),
                            ("lead_level", "Lead/Principal"),
                        ],
                        default="entry_level",
                        help_text="Target career level for this roadmap",
                        max_length=20,
                    ),
                ),
                (
                    "estimated_duration_weeks",
                    models.PositiveIntegerField(
                        help_text="Estimated total duration in weeks"
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        help_text="Overall difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "prerequisites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of prerequisites: [prerequisite1, prerequisite2, ...]",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Expected outcomes: [outcome1, outcome2, ...]",
                    ),
                ),
                (
                    "required_skills",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of required skill UUIDs: [uuid1, uuid2, ...]",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this template is available for users",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this template was used"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional template data (tags, categories, industry, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Template",
                "verbose_name_plural": "Roadmap Templates",
                "ordering": ["-usage_count", "title"],
                "indexes": [
                    models.Index(fields=["target_career"], name="idx_template_career"),
                    models.Index(fields=["career_level"], name="idx_template_level"),
                    models.Index(
                        fields=["is_published"], name="idx_template_published"
                    ),
                    models.Index(fields=["-usage_count"], name="idx_template_usage"),
                ],
            },
        ),
        migrations.AddField(
            model_name="roadmap",
            name="template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template this roadmap was based on (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roadmaps",
                to="roadmaps.roadmaptemplate",
            ),
        ),
        migrations.CreateModel(
            name="RoadmapCourse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Order of recommendation (1 = highest priority)",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary recommended course for this milestone",
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="AI-calculated match score (0-100) for this recommendation",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated explanation of why this course is recommended",
                    ),
                ),
                (
                    "is_enrolled",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has enrolled in this course",
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether user has completed this course",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user enrolled in this course",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When user completed this course",
                        null=True,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Recommended course from Course model",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_milestones",
                        to="courses.course",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        help_text="Milestone this course is recommended for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="roadmaps.roadmapmilestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Roadmap Course",
                "verbose_name_plural": "Roadmap Courses",
                "ordering": ["milestone", "order", "-is_primary", "-match_score"],
                "indexes": [
                    models.Index(
                        fields=["milestone"], name="idx_roadmapcourse_milestone"
                    ),
                    models.Index(fields=["course"], name="idx_roadmapcourse_course"),
                    models.Index(
                        fields=["is_primary"], name="idx_roadmapcourse_primary"
                    ),
                    models.Index(
                        fields=["-match_score"], name="idx_roadmapcourse_score"
                    ),
                ],
                "unique_together": {("milestone", "course")},
            },
        ),
        migrations.AddIndex(
            model_name="roadmapphase",
            index=models.Index(
                fields=["roadmap", "order"], name="idx_phase_roadmap_order"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapphase",
            index=models.Index(fields=["status"], name="idx_phase_status"),
        ),
        migrations.AlterUniqueTogether(
            name="roadmapphase",
            unique_together={("roadmap", "order")},
        ),
        migrations.AddIndex(
            model_name="roadmapmilestone",
            index=models.Index(
                fields=["phase", "order"], name="idx_milestone_phase_order"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapmilestone",
            index=models.Index(fields=["status"], name="idx_milestone_status"),
        ),
        migrations.AddIndex(
            model_name="roadmapmilestone",
            index=models.Index(fields=["milestone_type"], name="idx_milestone_type"),
        ),
        migrations.AlterUniqueTogether(
            name="roadmapmilestone",
            unique_together={("phase", "order")},
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["user"], name="idx_roadmap_user"),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["status"], name="idx_roadmap_status"),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["target_career"], name="idx_roadmap_career"),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(fields=["-created_at"], name="idx_roadmap_created"),
        ),
    ]
