# Generated by Django 5.0.14 on 2026-06-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("roadmaps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapmilestone",
            name="completed_from_assessment",
            field=models.BooleanField(
                default=False,
                help_text="True when this milestone was marked complete from the user's assessment baseline (already-mastered), not finished in-plan",
            ),
        ),
    ]
