# Generated by Django 5.0 on 2025-11-28 16:06

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePlatform",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Platform name (e.g., 'Udemy', 'Coursera', 'edX')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier (e.g., 'udemy', 'coursera')",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(
                        help_text="Main website URL of the platform", max_length=1000
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        help_text="Platform logo image URL",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief description of the platform"
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[
                            ("api", "API Integration"),
                            ("scraping", "Web Scraping"),
                            ("manual", "Manual Entry"),
                        ],
                        default="api",
                        help_text="How courses are fetched from this platform",
                        max_length=20,
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="Base URL for API integration (if applicable)",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "api_key_required",
                    models.BooleanField(
                        default=False,
                        help_text="Whether API key is required for integration",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this platform is actively being scraped/synced",
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time courses were synced from this platform",
                        null=True,
                    ),
                ),
                (
                    "total_courses",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of courses from this platform in our database",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional platform-specific configuration (API endpoints, scraping rules, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course Platform",
                "verbose_name_plural": "Course Platforms",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="idx_platform_slug"),
                    models.Index(fields=["is_active"], name="idx_platform_active"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Course ID on the external platform", max_length=255
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        db_index=True, help_text="Course title", max_length=500
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=255
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Course description/overview"
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief one-liner description",
                        max_length=500,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="Direct link to the course on the platform",
                        max_length=1000,
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True,
                        help_text="Course thumbnail/cover image URL",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("all_levels", "All Levels"),
                        ],
                        default="beginner",
                        help_text="Course difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "course_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Course"),
                            ("text", "Text-based Course"),
                            ("interactive", "Interactive Course"),
                            ("mixed", "Mixed Content"),
                        ],
                        default="video",
                        help_text="Primary content type",
                        max_length=20,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="English",
                        help_text="Primary language of instruction",
                        max_length=100,
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether the course is free",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Course price in USD (null if free or variable)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD",
                        help_text="Currency code (ISO 4217)",
                        max_length=10,
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total course duration in hours",
                        max_digits=6,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average user rating (0-5 scale)",
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of reviews/ratings"
                    ),
                ),
                (
                    "total_enrollments",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of students enrolled"
                    ),
                ),
                (
                    "total_lectures",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of lectures/lessons"
                    ),
                ),
                (
                    "total_resources",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of downloadable resources"
                    ),
                ),
                (
                    "instructors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of instructors: [{name, bio, avatar_url, rating}]",
                    ),
                ),
                (
                    "learning_outcomes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="What students will learn: [outcome1, outcome2, ...]",
                    ),
                ),
                (
                    "prerequisites",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Course prerequisites: [prerequisite1, prerequisite2, ...]",
                    ),
                ),
                (
                    "curriculum",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Course sections and lectures: [{section, lectures: [...]}]",
                    ),
                ),
                (
                    "has_certificate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether course provides a certificate upon completion",
                    ),
                ),
                (
                    "has_lifetime_access",
                    models.BooleanField(
                        default=False, help_text="Whether students get lifetime access"
                    ),
                ),
                (
                    "has_subtitles",
                    models.BooleanField(
                        default=False, help_text="Whether course has subtitles/captions"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Whether course is currently available on the platform",
                    ),
                ),
                (
                    "published_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the course was first published",
                        null=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the course content was last updated",
                        null=True,
                    ),
                ),
                (
                    "last_synced_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Last time this course data was synced from the platform",
                    ),
                ),
                (
                    "sync_error",
                    models.TextField(
                        blank=True, help_text="Error message if last sync failed"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Platform-specific data (tags, categories, affiliate links, etc.)",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="Platform where this course is hosted",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.courseplatform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course",
                "verbose_name_plural": "Courses",
                "ordering": ["-rating", "-total_enrollments"],
            },
        ),
        migrations.CreateModel(
            name="CourseSkill",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "proficiency_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="beginner",
                        help_text="Expected proficiency level after completing the course",
                        max_length=20,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a primary/core skill of the course",
                    ),
                ),
                (
                    "coverage_percentage",
                    models.PositiveIntegerField(
                        default=50,
                        help_text="How much of the course focuses on this skill (1-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Course that teaches this skill",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_skills",
                        to="courses.course",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        help_text="Skill taught in the course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_courses",
                        to="users.skill",
                    ),
                ),
            ],
            options={
                "verbose_name": "Course-Skill Relationship",
                "verbose_name_plural": "Course-Skill Relationships",
                "ordering": ["-is_primary", "-coverage_percentage"],
            },
        ),
        migrations.AddField(
            model_name="course",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                help_text="Skills taught in this course",
                related_name="courses",
                through="courses.CourseSkill",
                to="users.skill",
            ),
        ),
        migrations.AddIndex(
            model_name="courseskill",
            index=models.Index(
                fields=["course", "skill"], name="idx_courseskill_course_skill"
            ),
        ),
        migrations.AddIndex(
            model_name="courseskill",
            index=models.Index(fields=["skill"], name="idx_courseskill_skill"),
        ),
        migrations.AddIndex(
            model_name="courseskill",
            index=models.Index(fields=["is_primary"], name="idx_courseskill_primary"),
        ),
        migrations.AlterUniqueTogether(
            name="courseskill",
            unique_together={("course", "skill")},
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["platform", "external_id"], name="idx_course_platform_ext"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["title"], name="idx_course_title"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["level"], name="idx_course_level"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["is_free"], name="idx_course_free"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["rating"], name="idx_course_rating"),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["-total_enrollments"], name="idx_course_enrollments"
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(fields=["language"], name="idx_course_language"),
        ),
        migrations.AlterUniqueTogether(
            name="course",
            unique_together={("platform", "external_id")},
        ),
    ]
