# Generated by Django 5.0 on 2026-01-05 23:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Portfolio title (e.g., 'John Doe - Full Stack Developer')",
                        max_length=255,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Portfolio description or bio"
                    ),
                ),
                (
                    "projects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of project objects with title, description, images, links, technologies",
                    ),
                ),
                (
                    "achievements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of achievements, awards, recognitions",
                    ),
                ),
                (
                    "testimonials",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of testimonials and recommendations",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        default="default",
                        help_text="Portfolio theme/template (e.g., 'default', 'modern', 'minimal')",
                        max_length=100,
                    ),
                ),
                (
                    "custom_styles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom CSS/styling options as JSON",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this portfolio is publicly accessible",
                    ),
                ),
                (
                    "custom_url_slug",
                    models.SlugField(
                        blank=True,
                        help_text="Custom URL slug for public portfolio (e.g., 'john-doe')",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of views"
                    ),
                ),
                (
                    "last_viewed_at",
                    models.DateTimeField(
                        blank=True, help_text="Timestamp of last view", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this portfolio",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolios",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portfolio",
                "verbose_name_plural": "Portfolios",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_portfolio_user"
                    ),
                    models.Index(fields=["custom_url_slug"], name="idx_portfolio_slug"),
                    models.Index(fields=["is_public"], name="idx_portfolio_public"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Resume title (e.g., 'Software Engineer Resume', 'My Primary Resume')",
                        max_length=255,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        blank=True,
                        help_text="Template used for this resume (e.g., 'modern', 'classic', 'minimal')",
                        max_length=100,
                    ),
                ),
                (
                    "personal_info",
                    models.JSONField(
                        default=dict,
                        help_text="Personal information: name, email, phone, location, summary, etc.",
                    ),
                ),
                (
                    "work_experience",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of work experience objects with company, role, duration, achievements",
                    ),
                ),
                (
                    "education",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of education objects with institution, degree, field, dates",
                    ),
                ),
                (
                    "skills",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of skills with proficiency levels",
                    ),
                ),
                (
                    "certifications",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of certifications with name, issuer, date, expiry",
                    ),
                ),
                (
                    "projects",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of projects with title, description, technologies, links",
                    ),
                ),
                (
                    "languages",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Array of languages with proficiency levels",
                    ),
                ),
                (
                    "is_ats_optimized",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this resume has been optimized for ATS systems",
                    ),
                ),
                (
                    "ats_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="ATS optimization score (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "ats_suggestions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="AI-generated suggestions for improving ATS score",
                    ),
                ),
                (
                    "pdf_data",
                    models.BinaryField(
                        blank=True, help_text="Resume as PDF binary data", null=True
                    ),
                ),
                (
                    "docx_data",
                    models.BinaryField(
                        blank=True, help_text="Resume as DOCX binary data", null=True
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this is the user's primary/default resume",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Resume version number (for tracking revisions)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who owns this resume",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Resume",
                "verbose_name_plural": "Resumes",
                "ordering": ["-is_primary", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"], name="idx_resume_user"
                    ),
                    models.Index(
                        fields=["user", "is_primary"], name="idx_resume_primary"
                    ),
                    models.Index(fields=["-ats_score"], name="idx_resume_ats"),
                    models.Index(fields=["-created_at"], name="idx_resume_created"),
                ],
            },
        ),
    ]
