# Generated by Django 5.0 on 2026-01-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_tools", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="docx_data",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="pdf_data",
        ),
        migrations.AddField(
            model_name="resume",
            name="ats_error_message",
            field=models.TextField(
                blank=True, help_text="Error details if ATS processing failed"
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="ats_processing_status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="completed",
                help_text="Status of ATS optimization processing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="ats_task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async ATS processing",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="docx_file",
            field=models.FileField(
                blank=True,
                help_text="Resume as DOCX file",
                null=True,
                upload_to="resumes/docx/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="resume",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                help_text="Resume as PDF file",
                null=True,
                upload_to="resumes/pdf/%Y/%m/",
            ),
        ),
    ]
