"""Scenario corpus for ``role_key = "android"``.

Tier-1 stage-1 calibration content (single_choice, >=2 per calibration
subskill) authored as original internal content and human-reviewed. Identity
and governance fields (competency, dimension_key, doc_id, corpus_version) are
bound to the curated role graph so they cannot drift from the taxonomy.

Author additional scenarios here following ``AUTHOR_GUIDE.md``.
"""

from __future__ import annotations

from apps.assessments.scenario_corpus.schema import ScenarioDocument


SCENARIOS: list[ScenarioDocument] = [   {   'doc_id': 'android.rn_architecture.s1.single_choice.bridge',
        'role_key': 'android',
        'subskill_key': 'rn_architecture',
        'competency': 'RN Architecture',
        'dimension_key': 'react_native_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Understand how RN reaches native modules.',
        'scenario_context': 'A developer asks how JavaScript UI code invokes platform-native '
                            'capabilities in React Native.',
        'stem': 'Which layer carries calls between JS and native?',
        'options': [   {'id': 'a', 'label': 'The bridge or JSI layer'},
                       {'id': 'b', 'label': 'A direct DOM connection'},
                       {'id': 'c', 'label': 'An HTTP request to OS'},
                       {'id': 'd', 'label': 'A CSS stylesheet link'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'React Native runs JS separately and communicates over the bridge/JSI to '
                       'native modules and views.',
        'correct_answer_rationale': 'RN communicates across a bridge/JSI boundary to native '
                                    'modules.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'RN communicates across a bridge/JSI boundary to '
                                                  'native modules.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'React Native has no DOM; it renders native '
                                                  'views.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Native calls are in-process, not HTTP to the '
                                                  'OS.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Styling does not bridge to native modules.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.rn_architecture.s1.single_choice.native-module',
        'role_key': 'android',
        'subskill_key': 'rn_architecture',
        'competency': 'RN Architecture',
        'dimension_key': 'react_native_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Expose a missing native capability.',
        'scenario_context': 'An app needs a device feature not covered by existing React Native '
                            'APIs.',
        'stem': 'Which approach exposes that capability to JS?',
        'options': [   {'id': 'a', 'label': 'Write a bridged native module'},
                       {'id': 'b', 'label': 'Reimplement it in JS'},
                       {'id': 'c', 'label': 'Embed an iframe element'},
                       {'id': 'd', 'label': 'Use a CSS media query'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'When no JS API exists, implement a native module in Kotlin/Swift and '
                       'bridge it to JavaScript.',
        'correct_answer_rationale': 'A custom native module exposes platform APIs to the JS layer.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A custom native module exposes platform APIs to '
                                                  'the JS layer.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'JS cannot access platform-only capabilities '
                                                  'directly.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'React Native has no iframe element.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Media queries cannot access device '
                                                  'capabilities.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.hooks_mobile.s1.single_choice.usecallback-list',
        'role_key': 'android',
        'subskill_key': 'hooks_mobile',
        'competency': 'Hooks in Mobile',
        'dimension_key': 'react_core_for_mobile',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Stabilize callbacks passed to rows.',
        'scenario_context': 'A FlatList re-renders many rows because a new onPress function is '
                            'created every render.',
        'stem': 'Which hook keeps the row callback identity stable?',
        'options': [   {'id': 'a', 'label': 'useCallback for the handler'},
                       {'id': 'b', 'label': 'useState for the handler'},
                       {'id': 'c', 'label': 'useRef for the data'},
                       {'id': 'd', 'label': 'useContext for styles'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': "useCallback preserves a function's reference between renders, letting "
                       'memoized items avoid re-rendering.',
        'correct_answer_rationale': 'useCallback memoizes the function so memoized rows skip '
                                    'needless re-renders.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'useCallback memoizes the function so memoized '
                                                  'rows skip needless re-renders.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Storing a function in state does not stabilize '
                                                  'identity.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A ref to data does not memoize the callback.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Context for styling is unrelated to callback '
                                                  'identity.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.hooks_mobile.s1.single_choice.useeffect-focus',
        'role_key': 'android',
        'subskill_key': 'hooks_mobile',
        'competency': 'Hooks in Mobile',
        'dimension_key': 'react_core_for_mobile',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Run mobile effects on screen focus.',
        'scenario_context': 'Data should refresh each time a screen becomes focused, not only when '
                            'the component first mounts.',
        'stem': 'Which approach triggers refresh on every focus?',
        'options': [   {'id': 'a', 'label': 'A navigation focus effect'},
                       {'id': 'b', 'label': 'useEffect with empty deps'},
                       {'id': 'c', 'label': 'useMemo on the data'},
                       {'id': 'd', 'label': 'A plain module import'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Navigation focus effects re-run on each screen focus, unlike mount-only '
                       'useEffect.',
        'correct_answer_rationale': 'A focus effect re-runs whenever the screen regains focus.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A focus effect re-runs whenever the screen '
                                                  'regains focus.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'An empty array runs once on mount, missing '
                                                  'later focuses.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'useMemo caches a value; it does not react to '
                                                  'focus.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Imports do not run on focus.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.js_ui_thread.s1.single_choice.offload-work',
        'role_key': 'android',
        'subskill_key': 'js_ui_thread',
        'competency': 'JS vs UI Thread',
        'dimension_key': 'mobile_performance',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Keep heavy work off the UI thread.',
        'scenario_context': 'Animations stutter while a large JSON payload is parsed synchronously '
                            'on the JS thread.',
        'stem': 'Which approach reduces the dropped frames?',
        'options': [   {'id': 'a', 'label': 'Offload or defer the parsing'},
                       {'id': 'b', 'label': 'Increase the animation duration'},
                       {'id': 'c', 'label': 'Add more console logs'},
                       {'id': 'd', 'label': 'Disable the animation'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Long synchronous tasks block the JS thread; offloading or chunking them '
                       'keeps frames smooth.',
        'correct_answer_rationale': 'Offloading or chunking heavy work frees the thread driving UI '
                                    'updates.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Offloading or chunking heavy work frees the '
                                                  'thread driving UI updates.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Longer animations still stutter while the '
                                                  'thread is blocked.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Logging adds work and can worsen jank.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Removing the animation hides the symptom, not '
                                                  'the cause.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.js_ui_thread.s1.single_choice.native-driver',
        'role_key': 'android',
        'subskill_key': 'js_ui_thread',
        'competency': 'JS vs UI Thread',
        'dimension_key': 'mobile_performance',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Run animations on the native side.',
        'scenario_context': 'A fade animation must stay smooth even when JavaScript is briefly '
                            'busy.',
        'stem': 'Which setting runs it independent of JS?',
        'options': [   {'id': 'a', 'label': 'Enable the native driver'},
                       {'id': 'b', 'label': 'Run it in setInterval'},
                       {'id': 'c', 'label': 'Increase the JS heap'},
                       {'id': 'd', 'label': 'Log each animation frame'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'The native driver hands animation work to the native UI thread, so brief '
                       'JS busyness does not stutter.',
        'correct_answer_rationale': 'The native driver runs animations on the UI thread, immune to '
                                    'JS stalls.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'The native driver runs animations on the UI '
                                                  'thread, immune to JS stalls.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'JS timers are subject to the same thread '
                                                  'stalls.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Heap size does not move animation off the JS '
                                                  'thread.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Logging cannot offload the animation.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.stack_tab_drawer.s1.single_choice.stack-history',
        'role_key': 'android',
        'subskill_key': 'stack_tab_drawer',
        'competency': 'Stack/Tab/Drawer',
        'dimension_key': 'navigation',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Pick the push/pop navigator.',
        'scenario_context': 'Screens should push onto a history with a back gesture to return to '
                            'the previous screen.',
        'stem': 'Which navigator models this push/pop history?',
        'options': [   {'id': 'a', 'label': 'A stack navigator'},
                       {'id': 'b', 'label': 'A tab navigator'},
                       {'id': 'c', 'label': 'A drawer navigator'},
                       {'id': 'd', 'label': 'No navigator'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Stack navigation maintains an ordered history with push/pop and back '
                       'gestures.',
        'correct_answer_rationale': 'Stack navigators push and pop screens with back navigation.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Stack navigators push and pop screens with back '
                                                  'navigation.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Tabs switch peers without a push/pop history.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Drawers expose a side menu, not a screen '
                                                  'history.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Without a navigator there is no managed '
                                                  'history.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.stack_tab_drawer.s1.single_choice.tab-peers',
        'role_key': 'android',
        'subskill_key': 'stack_tab_drawer',
        'competency': 'Stack/Tab/Drawer',
        'dimension_key': 'navigation',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Choose tabs for sibling sections.',
        'scenario_context': 'An app has Home, Search, and Profile as equally important top-level '
                            'destinations switched frequently.',
        'stem': 'Which navigator best fits co-equal sections?',
        'options': [   {'id': 'a', 'label': 'A tab navigator'},
                       {'id': 'b', 'label': 'A deep push stack'},
                       {'id': 'c', 'label': 'A single scroll view'},
                       {'id': 'd', 'label': 'A modal per section'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Tab navigators suit a small set of co-equal sections; stacks suit '
                       'drill-down history.',
        'correct_answer_rationale': 'Tabs are ideal for switching among co-equal top-level '
                                    'destinations.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Tabs are ideal for switching among co-equal '
                                                  'top-level destinations.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Pushing peers onto a stack obscures their equal '
                                                  'status.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'One scroll view gives no distinct '
                                                  'destinations.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Modals interrupt flow and are not primary '
                                                  'navigation.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.optimistic_updates.s1.single_choice.instant-feedback',
        'role_key': 'android',
        'subskill_key': 'optimistic_updates',
        'competency': 'Optimistic Updates',
        'dimension_key': 'offline_and_data_sync',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Apply optimistic updates.',
        'scenario_context': 'Tapping like should feel instant even before the server confirms the '
                            'change.',
        'stem': 'Which approach gives immediate feedback?',
        'options': [   {'id': 'a', 'label': 'Update locally, reconcile later'},
                       {'id': 'b', 'label': 'Block until server responds'},
                       {'id': 'c', 'label': 'Ignore the server response'},
                       {'id': 'd', 'label': 'Reload the whole app'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Optimistic UI updates state immediately for responsiveness and reconciles '
                       'with the server result after.',
        'correct_answer_rationale': 'Optimistic updates apply locally, then confirm or revert on '
                                    'the response.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Optimistic updates apply locally, then confirm '
                                                  'or revert on the response.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Blocking makes the action feel slow.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Ignoring the response risks permanent '
                                                  'inconsistency.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'A full reload is the opposite of instant '
                                                  'feedback.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'android.optimistic_updates.s1.single_choice.rollback',
        'role_key': 'android',
        'subskill_key': 'optimistic_updates',
        'competency': 'Optimistic Updates',
        'dimension_key': 'offline_and_data_sync',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Handle optimistic-update failure.',
        'scenario_context': 'An optimistic like is applied locally, but the server request then '
                            'fails.',
        'stem': 'Which behavior keeps the UI consistent?',
        'options': [   {'id': 'a', 'label': 'Roll back and show error'},
                       {'id': 'b', 'label': 'Keep the change permanently'},
                       {'id': 'c', 'label': 'Retry forever unbounded'},
                       {'id': 'd', 'label': 'Crash the screen'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'When an optimistic request fails, revert to the prior state (optionally '
                       'retry with limits) to stay consistent.',
        'correct_answer_rationale': 'Reverting on failure restores consistency and informs the '
                                    'user.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Reverting on failure restores consistency and '
                                                  'informs the user.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Keeping a failed change leaves the UI '
                                                  'inconsistent.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Unbounded retries can hammer the server and '
                                                  'hang.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Crashing is not a recovery strategy.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'}]
