"""Scenario corpus for ``role_key = "data_science"``.

Tier-1 stage-1 calibration content (single_choice, >=2 per calibration
subskill) authored as original internal content and human-reviewed. Identity
and governance fields (competency, dimension_key, doc_id, corpus_version) are
bound to the curated role graph so they cannot drift from the taxonomy.

Author additional scenarios here following ``AUTHOR_GUIDE.md``.
"""

from __future__ import annotations

from apps.assessments.scenario_corpus.schema import ScenarioDocument


SCENARIOS: list[ScenarioDocument] = [   {   'doc_id': 'data_science.window_functions.s1.single_choice.running-total',
        'role_key': 'data_science',
        'subskill_key': 'window_functions',
        'competency': 'Window Functions',
        'dimension_key': 'sql_and_query_optimization',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Compute running totals with window functions.',
        'scenario_context': 'An analyst needs a cumulative revenue column per day without '
                            'collapsing the daily rows.',
        'stem': 'Which clause yields a running total per row?',
        'options': [   {'id': 'a', 'label': 'SUM with OVER ORDER BY'},
                       {'id': 'b', 'label': 'SUM with GROUP BY day'},
                       {'id': 'c', 'label': 'SUM with DISTINCT'},
                       {'id': 'd', 'label': 'SUM inside HAVING'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Window functions aggregate over a frame while preserving rows; ORDER BY in '
                       'OVER defines the running frame.',
        'correct_answer_rationale': 'An OVER clause with ORDER BY accumulates without grouping '
                                    'rows away.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'An OVER clause with ORDER BY accumulates '
                                                  'without grouping rows away.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'GROUP BY collapses rows into per-day totals, '
                                                  'not a running sum.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'DISTINCT deduplicates; it does not accumulate.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'HAVING filters groups and gives no per-row '
                                                  'cumulative value.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.window_functions.s1.single_choice.rank-partition',
        'role_key': 'data_science',
        'subskill_key': 'window_functions',
        'competency': 'Window Functions',
        'dimension_key': 'sql_and_query_optimization',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Rank within groups using PARTITION BY.',
        'scenario_context': "Each region's top-selling products must be ranked independently "
                            'within that region.',
        'stem': 'Which expression ranks products within each region?',
        'options': [   {'id': 'a', 'label': 'RANK with PARTITION BY region'},
                       {'id': 'b', 'label': 'RANK with global ORDER BY'},
                       {'id': 'c', 'label': 'Plain ORDER BY clause'},
                       {'id': 'd', 'label': 'GROUP BY region only'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'PARTITION BY divides rows into independent windows so ranking resets per '
                       'group.',
        'correct_answer_rationale': 'PARTITION BY restarts the ranking for each region.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'PARTITION BY restarts the ranking for each '
                                                  'region.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Without PARTITION BY the ranking spans all '
                                                  'regions.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Ordering alone assigns no rank numbers.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'GROUP BY aggregates and cannot emit per-row '
                                                  'ranks.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.batch_vs_streaming.s1.single_choice.latency',
        'role_key': 'data_science',
        'subskill_key': 'batch_vs_streaming',
        'competency': 'Batch vs Streaming',
        'dimension_key': 'data_pipeline_design',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Choose streaming for low-latency processing.',
        'scenario_context': 'A fraud system must score transactions within seconds of them '
                            'occurring.',
        'stem': 'Which processing model meets seconds-level latency?',
        'options': [   {'id': 'a', 'label': 'Stream processing'},
                       {'id': 'b', 'label': 'Nightly batch jobs'},
                       {'id': 'c', 'label': 'Manual weekly exports'},
                       {'id': 'd', 'label': 'One-time historical backfill'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Streaming suits event-time, low-latency needs; batch trades latency for '
                       'throughput.',
        'correct_answer_rationale': 'Streaming processes events as they arrive, giving low '
                                    'latency.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Streaming processes events as they arrive, '
                                                  'giving low latency.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Nightly batches add hours of delay, missing the '
                                                  'requirement.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Weekly exports are far too slow for real-time '
                                                  'scoring.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'A backfill is historical, not continuous '
                                                  'low-latency scoring.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.batch_vs_streaming.s1.single_choice.reprocessing',
        'role_key': 'data_science',
        'subskill_key': 'batch_vs_streaming',
        'competency': 'Batch vs Streaming',
        'dimension_key': 'data_pipeline_design',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Pick batch for large historical recomputation.',
        'scenario_context': 'A team must recompute a metric across three years of stored history '
                            'after a formula change.',
        'stem': 'Which approach fits a bounded recomputation?',
        'options': [   {'id': 'a', 'label': 'A batch job over history'},
                       {'id': 'b', 'label': 'A real-time event stream'},
                       {'id': 'c', 'label': 'Per-request computation'},
                       {'id': 'd', 'label': 'A websocket subscription'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Batch processing handles large, bounded, latency-tolerant workloads like '
                       'backfills efficiently.',
        'correct_answer_rationale': 'Batch is ideal for bounded, large, latency-tolerant '
                                    'reprocessing.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Batch is ideal for bounded, large, '
                                                  'latency-tolerant reprocessing.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Streaming handles new events, not a one-off '
                                                  'historical sweep.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Recomputing per request repeats work and is '
                                                  'slow at scale.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Websockets push live updates, unrelated to '
                                                  'historical recompute.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.star_schema.s1.single_choice.fact-dim',
        'role_key': 'data_science',
        'subskill_key': 'star_schema',
        'competency': 'Star Schema',
        'dimension_key': 'data_modeling',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Identify the fact table in a star schema.',
        'scenario_context': 'A sales mart stores measurable events alongside descriptive tables '
                            'for product, date, and store.',
        'stem': 'Which table is the fact table here?',
        'options': [   {'id': 'a', 'label': 'The sales measures table'},
                       {'id': 'b', 'label': 'The product description table'},
                       {'id': 'c', 'label': 'The date dimension table'},
                       {'id': 'd', 'label': 'The store dimension table'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'The central fact table holds measures and foreign keys; surrounding '
                       'dimensions hold context.',
        'correct_answer_rationale': 'The fact table stores numeric measures and keys to '
                                    'dimensions.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'The fact table stores numeric measures and keys '
                                                  'to dimensions.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Product is a descriptive dimension, not the '
                                                  'measured event.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Date is a dimension describing when events '
                                                  'happened.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Store is a dimension describing where events '
                                                  'happened.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.star_schema.s1.single_choice.denormalize',
        'role_key': 'data_science',
        'subskill_key': 'star_schema',
        'competency': 'Star Schema',
        'dimension_key': 'data_modeling',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Understand denormalized star dimensions.',
        'scenario_context': 'A modeler debates whether dimension tables should be fully normalized '
                            'or kept wide for analytics.',
        'stem': 'Which property typically describes star dimensions?',
        'options': [   {'id': 'a', 'label': 'Denormalized for simpler queries'},
                       {'id': 'b', 'label': 'Split into normalized sub-tables'},
                       {'id': 'c', 'label': 'Containing only the measures'},
                       {'id': 'd', 'label': 'Forbidding surrogate keys'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Star schemas favor denormalized dimensions to minimize joins and speed '
                       'analytics, trading some redundancy.',
        'correct_answer_rationale': 'Star dimensions are intentionally wide to reduce joins for '
                                    'analytics.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Star dimensions are intentionally wide to '
                                                  'reduce joins for analytics.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'That describes a snowflake schema, not a star.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Measures live in the fact table, not '
                                                  'dimensions.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Dimensions commonly use surrogate keys.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.spark_fundamentals.s1.single_choice.lazy-eval',
        'role_key': 'data_science',
        'subskill_key': 'spark_fundamentals',
        'competency': 'Spark Fundamentals',
        'dimension_key': 'distributed_data_processing',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Distinguish Spark transformations from actions.',
        'scenario_context': 'A developer chains map and filter on a DataFrame but no computation '
                            'runs until later.',
        'stem': 'Which operation actually triggers execution?',
        'options': [   {'id': 'a', 'label': 'An action like count'},
                       {'id': 'b', 'label': 'A transformation like select'},
                       {'id': 'c', 'label': 'Defining a UDF'},
                       {'id': 'd', 'label': 'Importing the Spark session'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Spark transformations are lazy; an action (count, collect, write) '
                       'materializes results.',
        'correct_answer_rationale': 'Actions like count() force Spark to execute the lazily-built '
                                    'plan.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Actions like count() force Spark to execute the '
                                                  'lazily-built plan.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Transformations are lazy and only build the '
                                                  'plan.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Defining a UDF does not trigger execution.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Importing the session does not run a job.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.spark_fundamentals.s1.single_choice.shuffle',
        'role_key': 'data_science',
        'subskill_key': 'spark_fundamentals',
        'competency': 'Spark Fundamentals',
        'dimension_key': 'distributed_data_processing',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Recognize the cost of wide transformations.',
        'scenario_context': 'A groupBy aggregation on a large dataset is slow because data moves '
                            'across the cluster.',
        'stem': 'Which term describes that cross-node data movement?',
        'options': [   {'id': 'a', 'label': 'A shuffle'},
                       {'id': 'b', 'label': 'A broadcast'},
                       {'id': 'c', 'label': 'A cache hit'},
                       {'id': 'd', 'label': 'A checkpoint'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Wide transformations require shuffles, the main Spark performance cost; '
                       'narrow ones avoid them.',
        'correct_answer_rationale': 'Wide transformations like groupBy repartition data across '
                                    'nodes via a shuffle.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Wide transformations like groupBy repartition '
                                                  'data across nodes via a shuffle.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Broadcast sends a small dataset to all nodes, '
                                                  'avoiding a shuffle.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Caching reuses computed partitions, not '
                                                  'cross-node movement.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Checkpointing persists lineage; it is not the '
                                                  'data movement.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.dbt_models.s1.single_choice.ref',
        'role_key': 'data_science',
        'subskill_key': 'dbt_models',
        'competency': 'dbt Models and Tests',
        'dimension_key': 'data_warehouse_and_lakehouse',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Use ref() to manage dbt dependencies.',
        'scenario_context': 'A dbt model selects from another model and the team wants the DAG and '
                            'schema resolved automatically.',
        'stem': 'Which function expresses the model dependency?',
        'options': [   {'id': 'a', 'label': 'The ref function'},
                       {'id': 'b', 'label': 'A hard-coded table name'},
                       {'id': 'c', 'label': 'The source function'},
                       {'id': 'd', 'label': 'A Python import'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'ref() is how dbt tracks model-to-model dependencies and resolves the right '
                       'relation per environment.',
        'correct_answer_rationale': 'ref builds the dependency graph and resolves the right schema '
                                    'per environment.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'ref builds the dependency graph and resolves '
                                                  'the right schema per environment.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Hard-coding breaks the DAG and environment '
                                                  'resolution.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'source references raw inputs, not other dbt '
                                                  'models.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'dbt models are SQL; imports do not wire the '
                                                  'DAG.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'data_science.dbt_models.s1.single_choice.tests',
        'role_key': 'data_science',
        'subskill_key': 'dbt_models',
        'competency': 'dbt Models and Tests',
        'dimension_key': 'data_warehouse_and_lakehouse',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Add data tests to dbt models.',
        'scenario_context': 'A team wants to fail the build automatically when a primary key '
                            'column contains duplicates or nulls.',
        'stem': 'Which dbt tests enforce that key integrity?',
        'options': [   {'id': 'a', 'label': 'The unique and not_null tests'},
                       {'id': 'b', 'label': 'A descriptive code comment'},
                       {'id': 'c', 'label': 'A downstream dashboard filter'},
                       {'id': 'd', 'label': 'Renaming the column to id'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'dbt schema tests (unique, not_null, relationships) gate the build, '
                       'catching data-quality regressions.',
        'correct_answer_rationale': 'The built-in unique and not_null tests fail the run on '
                                    'violations.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'The built-in unique and not_null tests fail the '
                                                  'run on violations.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Comments document intent but enforce nothing.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Dashboards hide bad rows rather than catching '
                                                  'them.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Naming does not validate uniqueness or '
                                                  'nullability.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'}]
