"""Scenario corpus for ``role_key = "devops"``.

Tier-1 stage-1 calibration content (single_choice, >=2 per calibration
subskill) authored as original internal content and human-reviewed. Identity
and governance fields (competency, dimension_key, doc_id, corpus_version) are
bound to the curated role graph so they cannot drift from the taxonomy.

Author additional scenarios here following ``AUTHOR_GUIDE.md``.
"""

from __future__ import annotations

from apps.assessments.scenario_corpus.schema import ScenarioDocument


SCENARIOS: list[ScenarioDocument] = [   {   'doc_id': 'devops.dockerfile_best_practices.s1.single_choice.layer-cache',
        'role_key': 'devops',
        'subskill_key': 'dockerfile_best_practices',
        'competency': 'Dockerfile Best Practices',
        'dimension_key': 'containerization',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Order Dockerfile steps for cache reuse.',
        'scenario_context': 'Every code change reinstalls all dependencies because the Dockerfile '
                            'copies the whole source before installing.',
        'stem': 'Which reordering restores dependency-layer caching?',
        'options': [   {'id': 'a', 'label': 'Copy lockfile and install first'},
                       {'id': 'b', 'label': 'Copy everything then install'},
                       {'id': 'c', 'label': 'Disable the build cache'},
                       {'id': 'd', 'label': 'Install at container start'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Copying dependency manifests and installing before the app source keeps '
                       'the install layer cached.',
        'correct_answer_rationale': 'Installing from the lockfile first lets that layer cache '
                                    'until deps change.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Installing from the lockfile first lets that '
                                                  'layer cache until deps change.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Any source change busts the cache and '
                                                  'reinstalls deps.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Disabling cache makes every build slow.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Runtime installs slow startup and lose '
                                                  'immutability.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.dockerfile_best_practices.s1.single_choice.image-size',
        'role_key': 'devops',
        'subskill_key': 'dockerfile_best_practices',
        'competency': 'Dockerfile Best Practices',
        'dimension_key': 'containerization',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Reduce image size with multi-stage builds.',
        'scenario_context': 'A production image is large because it ships compilers and build '
                            'tools only needed at build time.',
        'stem': 'Which technique keeps build tools out of it?',
        'options': [   {'id': 'a', 'label': 'Use a multi-stage build'},
                       {'id': 'b', 'label': 'Add more RUN layers'},
                       {'id': 'c', 'label': 'Run apt-get upgrade last'},
                       {'id': 'd', 'label': 'Set a larger memory limit'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Multi-stage builds compile in one stage and copy only needed artifacts '
                       'into a minimal runtime stage.',
        'correct_answer_rationale': 'Multi-stage builds discard build-only tooling, shipping just '
                                    'runtime artifacts.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Multi-stage builds discard build-only tooling, '
                                                  'shipping just runtime artifacts.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Extra layers do not remove build tooling from '
                                                  'the image.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Upgrading packages does not drop build '
                                                  'dependencies.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Memory limits do not affect image size.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.k8s_deployments.s1.single_choice.rolling-update',
        'role_key': 'devops',
        'subskill_key': 'k8s_deployments',
        'competency': 'Deployments and Services',
        'dimension_key': 'kubernetes',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Achieve zero-downtime updates.',
        'scenario_context': 'A team wants new pods rolled out gradually while old pods keep '
                            'serving until replacements are ready.',
        'stem': 'Which Kubernetes object provides rolling updates?',
        'options': [   {'id': 'a', 'label': 'A Deployment'},
                       {'id': 'b', 'label': 'A bare Pod'},
                       {'id': 'c', 'label': 'A ConfigMap'},
                       {'id': 'd', 'label': 'A Secret'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Deployments orchestrate ReplicaSets for controlled rolling updates and '
                       'rollbacks.',
        'correct_answer_rationale': 'Deployments manage ReplicaSets with rolling updates and '
                                    'rollbacks.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Deployments manage ReplicaSets with rolling '
                                                  'updates and rollbacks.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'A standalone Pod has no rollout or self-healing '
                                                  'management.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'ConfigMaps hold configuration, not rollout '
                                                  'logic.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Secrets store sensitive data, not deployment '
                                                  'strategy.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.k8s_deployments.s1.single_choice.service-discovery',
        'role_key': 'devops',
        'subskill_key': 'k8s_deployments',
        'competency': 'Deployments and Services',
        'dimension_key': 'kubernetes',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Expose pods with a stable address.',
        'scenario_context': 'Pod IPs change as pods restart, breaking clients that target '
                            'individual pods directly.',
        'stem': 'Which object gives a stable load-balanced address?',
        'options': [   {'id': 'a', 'label': 'A Service'},
                       {'id': 'b', 'label': 'A single Pod IP'},
                       {'id': 'c', 'label': 'A Namespace'},
                       {'id': 'd', 'label': 'A PersistentVolume'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'A Service abstracts pods behind a stable address and load-balances '
                       'requests.',
        'correct_answer_rationale': 'A Service provides a stable ClusterIP/DNS name and balances '
                                    'traffic to pods.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A Service provides a stable ClusterIP/DNS name '
                                                  'and balances traffic to pods.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Pod IPs are ephemeral and change on restart.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Namespaces scope resources; they do not route '
                                                  'traffic.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'PVs provide storage, not network endpoints.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.pipeline_as_code.s1.single_choice.versioned-pipeline',
        'role_key': 'devops',
        'subskill_key': 'pipeline_as_code',
        'competency': 'Pipeline as Code',
        'dimension_key': 'ci_cd_pipelines',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Keep CI pipelines in version control.',
        'scenario_context': 'A team configures builds by clicking through a UI, and changes are '
                            'untracked and hard to review.',
        'stem': 'Which practice makes changes reviewable?',
        'options': [   {'id': 'a', 'label': 'Define pipeline in config file'},
                       {'id': 'b', 'label': 'Configure jobs only in UI'},
                       {'id': 'c', 'label': 'Email build steps around'},
                       {'id': 'd', 'label': 'Keep steps in a notebook'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Pipeline-as-code stores CI/CD definitions in the repo for review, history, '
                       'and reproducibility.',
        'correct_answer_rationale': 'Pipeline-as-code is versioned, reviewable, and reproducible '
                                    'like source.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Pipeline-as-code is versioned, reviewable, and '
                                                  'reproducible like source.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'UI-only changes are untracked and '
                                                  'unreviewable.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Email is not version-controlled or '
                                                  'enforceable.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Private notes are neither shared nor '
                                                  'reproducible.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.pipeline_as_code.s1.single_choice.fail-fast',
        'role_key': 'devops',
        'subskill_key': 'pipeline_as_code',
        'competency': 'Pipeline as Code',
        'dimension_key': 'ci_cd_pipelines',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Order CI stages to fail fast.',
        'scenario_context': 'Slow end-to-end tests run before quick linting, so trivial errors '
                            'waste long pipeline minutes.',
        'stem': 'Which ordering surfaces cheap failures soonest?',
        'options': [   {'id': 'a', 'label': 'Run fast checks before slow'},
                       {'id': 'b', 'label': 'Run e2e tests first'},
                       {'id': 'c', 'label': 'Run stages in random order'},
                       {'id': 'd', 'label': 'Skip unit tests entirely'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Ordering pipelines cheap-to-expensive gives fast feedback and conserves '
                       'resources.',
        'correct_answer_rationale': 'Cheap, fast checks first fail quickly on trivial errors, '
                                    'saving compute.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Cheap, fast checks first fail quickly on '
                                                  'trivial errors, saving compute.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'That delays trivial failures until after '
                                                  'expensive steps.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Random ordering gives no fail-fast guarantee.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Skipping tests removes the cheapest safety '
                                                  'net.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.terraform_modules.s1.single_choice.dry-module',
        'role_key': 'devops',
        'subskill_key': 'terraform_modules',
        'competency': 'Terraform Modules',
        'dimension_key': 'infrastructure_as_code',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Reuse infrastructure with modules.',
        'scenario_context': 'Three environments duplicate near-identical resource blocks, and '
                            'edits must be repeated in each.',
        'stem': 'Which Terraform feature removes this duplication?',
        'options': [   {'id': 'a', 'label': 'Extract a reusable module'},
                       {'id': 'b', 'label': 'Copy the tf files'},
                       {'id': 'c', 'label': 'Hard-code values per file'},
                       {'id': 'd', 'label': 'Disable the state files'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Modules encapsulate reusable resource groups with input variables, giving '
                       'one source of truth.',
        'correct_answer_rationale': 'A module is parameterized and reused across environments from '
                                    'one definition.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A module is parameterized and reused across '
                                                  'environments from one definition.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Copying is the duplication causing the drift.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Hard-coding worsens duplication and drift.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Removing state breaks Terraform tracking '
                                                  'entirely.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.terraform_modules.s1.single_choice.remote-state',
        'role_key': 'devops',
        'subskill_key': 'terraform_modules',
        'competency': 'Terraform Modules',
        'dimension_key': 'infrastructure_as_code',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Share Terraform state safely.',
        'scenario_context': "Team members overwrite each other's local state, causing conflicting "
                            'applies.',
        'stem': 'Which configuration prevents conflicting applies?',
        'options': [   {'id': 'a', 'label': 'Remote backend with locking'},
                       {'id': 'b', 'label': 'State committed per laptop'},
                       {'id': 'c', 'label': 'State emailed around'},
                       {'id': 'd', 'label': 'State deleted each apply'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'A remote backend with locking centralizes state and prevents concurrent '
                       'applies from corrupting it.',
        'correct_answer_rationale': 'A locking remote backend serializes applies and shares one '
                                    'state.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A locking remote backend serializes applies and '
                                                  'shares one state.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Local copies diverge and conflict.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Manual sharing has no locking and invites '
                                                  'overwrites.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Destroying state loses tracking and risks '
                                                  'recreation.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.iam_least_privilege.s1.single_choice.scoped-policy',
        'role_key': 'devops',
        'subskill_key': 'iam_least_privilege',
        'competency': 'IAM Least Privilege',
        'dimension_key': 'cloud_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Apply least privilege to policies.',
        'scenario_context': 'A service that only reads one bucket is currently granted full '
                            'administrator access.',
        'stem': 'Which policy change follows least privilege?',
        'options': [   {'id': 'a', 'label': 'Grant read-only on bucket'},
                       {'id': 'b', 'label': 'Keep full admin access'},
                       {'id': 'c', 'label': 'Share the root credentials'},
                       {'id': 'd', 'label': 'Disable IAM entirely'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Least privilege scopes permissions to exactly what the workload needs, '
                       'minimizing risk.',
        'correct_answer_rationale': 'Least privilege grants only the permissions the task '
                                    'requires.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Least privilege grants only the permissions the '
                                                  'task requires.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Over-broad access maximizes blast radius if '
                                                  'compromised.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Root sharing is the opposite of least '
                                                  'privilege.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Allowing everything removes access control.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'devops.iam_least_privilege.s1.single_choice.roles-vs-keys',
        'role_key': 'devops',
        'subskill_key': 'iam_least_privilege',
        'competency': 'IAM Least Privilege',
        'dimension_key': 'cloud_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Prefer roles over long-lived keys.',
        'scenario_context': 'An application on a cloud VM authenticates with static access keys '
                            'checked into config.',
        'stem': 'Which approach removes the static credentials?',
        'options': [   {'id': 'a', 'label': 'Assign an instance role'},
                       {'id': 'b', 'label': 'Embed the keys in image'},
                       {'id': 'c', 'label': 'Print the keys to logs'},
                       {'id': 'd', 'label': 'Reuse one key everywhere'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Workload identities issue temporary, auto-rotated credentials, eliminating '
                       'embedded long-lived keys.',
        'correct_answer_rationale': 'Instance roles supply rotated, short-lived credentials with '
                                    'no static secret.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Instance roles supply rotated, short-lived '
                                                  'credentials with no static secret.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Baking keys in spreads a static secret '
                                                  'further.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Logging secrets leaks them broadly.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Shared static keys widen blast radius and '
                                                  'complicate rotation.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'}]
