"""Scenario corpus for ``role_key = "fullstack"``.

Tier-1 stage-1 calibration content (single_choice, >=2 per calibration
subskill) authored as original internal content and human-reviewed. Identity
and governance fields (competency, dimension_key, doc_id, corpus_version) are
bound to the curated role graph so they cannot drift from the taxonomy.

Author additional scenarios here following ``AUTHOR_GUIDE.md``.
"""

from __future__ import annotations

from apps.assessments.scenario_corpus.schema import ScenarioDocument


SCENARIOS: list[ScenarioDocument] = [   {   'doc_id': 'fullstack.fe_js_closures.s1.single_choice.memoize',
        'role_key': 'fullstack',
        'subskill_key': 'fe_js_closures',
        'competency': 'Closures and Scope',
        'dimension_key': 'fe_javascript_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Use a closure to cache results.',
        'scenario_context': 'A pure formatter is expensive, and the team wants to cache results '
                            'per input across calls without a global cache.',
        'stem': 'Which technique caches results yet stays private?',
        'options': [   {'id': 'a', 'label': 'Close over a local cache'},
                       {'id': 'b', 'label': 'Recompute on every call'},
                       {'id': 'c', 'label': 'Store results globally'},
                       {'id': 'd', 'label': 'Disable the formatter entirely'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'A memoizing closure keeps its cache in the enclosing scope: persistent yet '
                       'unreachable from outside.',
        'correct_answer_rationale': 'The cache lives in the factory scope, private yet persistent '
                                    'across calls.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'The cache lives in the factory scope, private '
                                                  'yet persistent across calls.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Recomputing defeats the goal of caching.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A global cache is exposed and collision-prone.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Disabling the feature is not a caching '
                                                  'strategy.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.fe_js_closures.s1.single_choice.stale-binding',
        'role_key': 'fullstack',
        'subskill_key': 'fe_js_closures',
        'competency': 'Closures and Scope',
        'dimension_key': 'fe_javascript_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Diagnose stale closures over changing values.',
        'scenario_context': 'An event handler defined once reads a count variable but always sees '
                            'the original value after updates.',
        'stem': 'Which explanation fits the stale value read?',
        'options': [   {'id': 'a', 'label': 'Handler closed over old binding'},
                       {'id': 'b', 'label': 'The variable was frozen'},
                       {'id': 'c', 'label': 'The event never fired'},
                       {'id': 'd', 'label': 'The value lives in cookies'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Closures capture bindings, not live snapshots; a handler created once must '
                       'be recreated to see newer values.',
        'correct_answer_rationale': 'A closure captures the binding at creation; without '
                                    'recreating it, it reads the old value.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A closure captures the binding at creation; '
                                                  'without recreating it, it reads the old value.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'freeze affects object mutation, not closure '
                                                  'capture of a number.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'The handler does run; it just reads a stale '
                                                  'value.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Cookies are unrelated to in-memory closure '
                                                  'capture.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.fe_component_composition.s1.single_choice.render-prop',
        'role_key': 'fullstack',
        'subskill_key': 'fe_component_composition',
        'competency': 'Component Composition',
        'dimension_key': 'fe_react_core',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Share behavior with a render prop.',
        'scenario_context': 'A MouseTracker must share pointer coordinates with different visual '
                            'outputs chosen by the parent.',
        'stem': 'Which pattern lets the parent render the data?',
        'options': [   {'id': 'a', 'label': 'Children as a function'},
                       {'id': 'b', 'label': 'Hard-code one output'},
                       {'id': 'c', 'label': 'Emit a DOM event only'},
                       {'id': 'd', 'label': 'Store coordinates in storage'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Render props (children-as-function) invert rendering control to the parent '
                       'while the component owns behavior.',
        'correct_answer_rationale': 'A function-as-children lets the parent render any UI from the '
                                    'shared data.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A function-as-children lets the parent render '
                                                  'any UI from the shared data.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Hard-coding prevents the parent from choosing '
                                                  'the visual.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'DOM events bypass React composition and are '
                                                  'awkward to render.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Persistence is unrelated to flexible '
                                                  'rendering.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.fe_component_composition.s1.single_choice.container-presentational',
        'role_key': 'fullstack',
        'subskill_key': 'fe_component_composition',
        'competency': 'Component Composition',
        'dimension_key': 'fe_react_core',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Separate data fetching from presentation.',
        'scenario_context': 'A list component mixes API calls, state, and markup, making it hard '
                            'to reuse the visuals elsewhere.',
        'stem': 'Which split improves reuse of the visual list?',
        'options': [   {'id': 'a', 'label': 'Extract a presentational component'},
                       {'id': 'b', 'label': 'Move markup into the API'},
                       {'id': 'c', 'label': 'Inline fetch into each consumer'},
                       {'id': 'd', 'label': 'Render inside a web worker'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Splitting container (data) from presentational (props-only UI) makes '
                       'visuals reusable and testable.',
        'correct_answer_rationale': 'A pure presentational component is reusable wherever items '
                                    'are supplied.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A pure presentational component is reusable '
                                                  'wherever items are supplied.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Markup does not belong in the data layer.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Inlining duplicates fetching and couples '
                                                  'consumers to the API.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Workers cannot touch the DOM and do not aid '
                                                  'reuse.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.be_decorators.s1.single_choice.wraps',
        'role_key': 'fullstack',
        'subskill_key': 'be_decorators',
        'competency': 'Decorators',
        'dimension_key': 'be_python_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Preserve function metadata in decorators.',
        'scenario_context': 'A logging decorator wraps view functions, but help() and __name__ now '
                            'report the wrapper instead of the original.',
        'stem': 'Which addition restores the wrapped metadata?',
        'options': [   {'id': 'a', 'label': 'Apply functools.wraps to wrapper'},
                       {'id': 'b', 'label': 'Return the original unchanged'},
                       {'id': 'c', 'label': 'Rename the wrapper manually'},
                       {'id': 'd', 'label': 'Add a global try-except'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'functools.wraps propagates identity and docs so introspection and tooling '
                       'keep working.',
        'correct_answer_rationale': 'functools.wraps copies __name__, __doc__, and signature onto '
                                    'the wrapper.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'functools.wraps copies __name__, __doc__, and '
                                                  'signature onto the wrapper.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': "That removes the decorator's added behavior."},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Copying one attribute misses doc and signature '
                                                  'metadata.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Error handling does not restore metadata.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.be_decorators.s1.single_choice.arguments',
        'role_key': 'fullstack',
        'subskill_key': 'be_decorators',
        'competency': 'Decorators',
        'dimension_key': 'be_python_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Forward arbitrary arguments through a decorator.',
        'scenario_context': 'A timing decorator must wrap functions with varied signatures without '
                            'breaking their calls.',
        'stem': 'Which wrapper signature forwards all arguments?',
        'options': [   {'id': 'a', 'label': 'Accept args and kwargs'},
                       {'id': 'b', 'label': 'Accept only self'},
                       {'id': 'c', 'label': 'Accept no parameters'},
                       {'id': 'd', 'label': 'Accept one positional name'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Using *args/**kwargs lets one decorator wrap functions of any signature '
                       'without altering calls.',
        'correct_answer_rationale': '*args and **kwargs forward all positional and keyword '
                                    'arguments transparently.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': '*args and **kwargs forward all positional and '
                                                  'keyword arguments transparently.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'A fixed signature breaks functions with '
                                                  'different parameters.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': "It cannot accept the wrapped function's "
                                                  'arguments.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'A single positional name misses keywords or '
                                                  'extra args.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.be_select_related_prefetch.s1.single_choice.n-plus-one',
        'role_key': 'fullstack',
        'subskill_key': 'be_select_related_prefetch',
        'competency': 'select_related / prefetch_related',
        'dimension_key': 'be_django_orm',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Eliminate N+1 queries in Django ORM.',
        'scenario_context': 'A template loops over orders and accesses each order.customer, '
                            'triggering one query per order.',
        'stem': 'Which change collapses the per-row customer queries?',
        'options': [   {'id': 'a', 'label': 'Use select_related on customer'},
                       {'id': 'b', 'label': 'Call all twice'},
                       {'id': 'c', 'label': 'Wrap loop in atomic'},
                       {'id': 'd', 'label': 'Add order_by customer'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'select_related uses a join for forward foreign keys, removing the '
                       'one-query-per-access pattern.',
        'correct_answer_rationale': 'select_related does a SQL join, fetching customers in the '
                                    'same query.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'select_related does a SQL join, fetching '
                                                  'customers in the same query.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Re-querying does not join related rows.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Transactions control commits, not query count.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Ordering does not prefetch the related rows.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.be_select_related_prefetch.s1.single_choice.prefetch-m2m',
        'role_key': 'fullstack',
        'subskill_key': 'be_select_related_prefetch',
        'competency': 'select_related / prefetch_related',
        'dimension_key': 'be_django_orm',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Choose prefetch_related for many-valued relations.',
        'scenario_context': 'Each article has many tags accessed in a loop, and select_related '
                            'does not apply to the many-to-many.',
        'stem': 'Which method efficiently loads all the tags?',
        'options': [   {'id': 'a', 'label': 'Use prefetch_related on tags'},
                       {'id': 'b', 'label': 'Use select_related on tags'},
                       {'id': 'c', 'label': 'Use only on tags'},
                       {'id': 'd', 'label': 'Use values on tags'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'prefetch_related handles many-to-many and reverse relations with a batched '
                       'second query.',
        'correct_answer_rationale': 'prefetch_related runs a second query and joins in Python for '
                                    'many-to-many.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'prefetch_related runs a second query and joins '
                                                  'in Python for many-to-many.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'select_related cannot span many-to-many '
                                                  'relations.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'only limits columns; it does not prefetch '
                                                  'related rows.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'values returns dicts and still issues per-row '
                                                  'queries.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.fe_responsive_css.s1.single_choice.fluid-units',
        'role_key': 'fullstack',
        'subskill_key': 'fe_responsive_css',
        'competency': 'Responsive CSS',
        'dimension_key': 'fe_css_layout_styling',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Use relative units for scalable typography.',
        'scenario_context': 'Font sizes set in pixels do not scale when users change their '
                            "browser's base font size.",
        'stem': 'Which unit respects the base font-size preference?',
        'options': [   {'id': 'a', 'label': 'The rem unit'},
                       {'id': 'b', 'label': 'The px unit'},
                       {'id': 'c', 'label': 'The vh unit'},
                       {'id': 'd', 'label': 'The deg unit'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'rem cascades from the root font-size, respecting user zoom and '
                       'accessibility settings.',
        'correct_answer_rationale': "rem scales from the root font-size, honoring the user's "
                                    'preference.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'rem scales from the root font-size, honoring '
                                                  "the user's preference."},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'px is absolute and ignores the base font-size '
                                                  'setting.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'vh tracks viewport height, not the base font '
                                                  'size.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'deg is an angle unit and not a length.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'fullstack.fe_responsive_css.s1.single_choice.container-overflow',
        'role_key': 'fullstack',
        'subskill_key': 'fe_responsive_css',
        'competency': 'Responsive CSS',
        'dimension_key': 'fe_css_layout_styling',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Prevent horizontal overflow.',
        'scenario_context': 'A fixed-width inner element causes a horizontal scrollbar on narrow '
                            'screens.',
        'stem': 'Which rule lets the element shrink to fit?',
        'options': [   {'id': 'a', 'label': 'Set max-width to full'},
                       {'id': 'b', 'label': 'Set a fixed pixel width'},
                       {'id': 'c', 'label': 'Use fixed positioning'},
                       {'id': 'd', 'label': 'Set white-space to nowrap'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'max-width: 100% (with width auto) keeps elements within their container '
                       'across viewports.',
        'correct_answer_rationale': 'max-width 100% caps the element to its container, preventing '
                                    'overflow.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'max-width 100% caps the element to its '
                                                  'container, preventing overflow.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'A fixed width forces overflow on narrow '
                                                  'screens.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Fixed positioning does not constrain width to '
                                                  'the container.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'nowrap increases overflow by preventing '
                                                  'wrapping.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'}]
