"""Scenario corpus for ``role_key = "machine_learning_engineer"``.

Tier-1 stage-1 calibration content (single_choice, >=2 per calibration
subskill) authored as original internal content and human-reviewed. Identity
and governance fields (competency, dimension_key, doc_id, corpus_version) are
bound to the curated role graph so they cannot drift from the taxonomy.

Author additional scenarios here following ``AUTHOR_GUIDE.md``.
"""

from __future__ import annotations

from apps.assessments.scenario_corpus.schema import ScenarioDocument


SCENARIOS: list[ScenarioDocument] = [   {   'doc_id': 'machine_learning_engineer.bias_variance.s1.single_choice.overfit',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'bias_variance',
        'competency': 'Bias-Variance Tradeoff',
        'dimension_key': 'ml_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Diagnose high variance (overfitting).',
        'scenario_context': 'A model scores 99% on training data but 70% on validation data.',
        'stem': 'Which condition does this large gap indicate?',
        'options': [   {'id': 'a', 'label': 'High variance, overfitting'},
                       {'id': 'b', 'label': 'High bias, underfitting'},
                       {'id': 'c', 'label': 'A perfectly balanced fit'},
                       {'id': 'd', 'label': 'Label leakage in validation'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'A wide gap between strong training and weak validation indicates high '
                       'variance; fix with regularization or data.',
        'correct_answer_rationale': 'A large train-minus-validation gap is the signature of '
                                    'overfitting.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'A large train-minus-validation gap is the '
                                                  'signature of overfitting.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Underfitting shows low training accuracy too, '
                                                  'not a large gap.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A 29-point gap is not a balanced fit.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Leakage usually inflates validation, not '
                                                  'depresses it.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.bias_variance.s1.single_choice.underfit-fix',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'bias_variance',
        'competency': 'Bias-Variance Tradeoff',
        'dimension_key': 'ml_fundamentals',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Address high bias with capacity.',
        'scenario_context': 'A linear model underperforms on both training and validation sets for '
                            'a clearly non-linear relationship.',
        'stem': 'Which change most directly reduces this high bias?',
        'options': [   {'id': 'a', 'label': 'Increase capacity or features'},
                       {'id': 'b', 'label': 'Add stronger L2 regularization'},
                       {'id': 'c', 'label': 'Collect more identical features'},
                       {'id': 'd', 'label': 'Reduce the feature count'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'High bias is reduced by increasing capacity or adding informative '
                       'features, not more regularization.',
        'correct_answer_rationale': 'More capacity or expressive features let the model fit the '
                                    'signal.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'More capacity or expressive features let the '
                                                  'model fit the signal.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'More regularization increases bias, worsening '
                                                  'underfitting.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'More rows do not fix a model too simple to '
                                                  'capture the pattern.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Fewer features further limit an underfitting '
                                                  'model.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.training_serving_skew.s1.single_choice.feature-parity',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'training_serving_skew',
        'competency': 'Training/Serving Skew',
        'dimension_key': 'ml_system_design',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Prevent training/serving skew.',
        'scenario_context': 'A feature computed one way in training is computed differently at '
                            'serving time, hurting live accuracy.',
        'stem': 'Which practice most directly prevents this skew?',
        'options': [   {'id': 'a', 'label': 'Share one transformation implementation'},
                       {'id': 'b', 'label': 'Retrain more frequently'},
                       {'id': 'c', 'label': 'Increase the model size'},
                       {'id': 'd', 'label': 'Lower the decision threshold'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Skew is best avoided by sharing feature logic (feature store or shared '
                       'library) across both paths.',
        'correct_answer_rationale': 'Reusing the same code guarantees identical features in both '
                                    'paths.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Reusing the same code guarantees identical '
                                                  'features in both paths.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Retraining does not fix divergent feature '
                                                  'logic.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A bigger model still receives inconsistent '
                                                  'features.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Threshold tuning masks but does not remove '
                                                  'skew.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.training_serving_skew.s1.single_choice.data-leak-time',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'training_serving_skew',
        'competency': 'Training/Serving Skew',
        'dimension_key': 'ml_system_design',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Avoid using unavailable features at serving.',
        'scenario_context': 'A feature uses an aggregate that, at serving time, is unavailable '
                            'until after the prediction is needed.',
        'stem': 'Which issue does relying on that aggregate create?',
        'options': [   {'id': 'a', 'label': 'Training and serving skew'},
                       {'id': 'b', 'label': 'Improved real-time latency'},
                       {'id': 'c', 'label': 'Reduced training time'},
                       {'id': 'd', 'label': 'Better probability calibration'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Features must be computable with information available at prediction time, '
                       'or serving inputs differ from training.',
        'correct_answer_rationale': 'If a feature cannot be computed at serve time, train and '
                                    'serve inputs diverge.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'If a feature cannot be computed at serve time, '
                                                  'train and serve inputs diverge.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Missing features degrade, not improve, '
                                                  'serving.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'It is unrelated to training duration.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Unavailable features do not improve '
                                                  'calibration.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.hyperparameter_tuning.s1.single_choice.val-set',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'hyperparameter_tuning',
        'competency': 'Hyperparameter Tuning',
        'dimension_key': 'model_training_and_experimentation',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Tune without touching the test set.',
        'scenario_context': 'A team is choosing a learning rate and wants an unbiased final '
                            'performance estimate.',
        'stem': 'Which split should drive hyperparameter selection?',
        'options': [   {'id': 'a', 'label': 'A validation set'},
                       {'id': 'b', 'label': 'The test set directly'},
                       {'id': 'c', 'label': 'The training set only'},
                       {'id': 'd', 'label': 'Random unlabeled data'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Hyperparameters are selected on validation data; the test set is reserved '
                       'for one final evaluation.',
        'correct_answer_rationale': 'Tuning on validation preserves the test set as an unbiased '
                                    'estimate.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Tuning on validation preserves the test set as '
                                                  'an unbiased estimate.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Tuning on test leaks information and biases the '
                                                  'estimate.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Selecting on training alone overfits '
                                                  'hyperparameters.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Unlabeled data cannot score hyperparameters.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.hyperparameter_tuning.s1.single_choice.search-strategy',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'hyperparameter_tuning',
        'competency': 'Hyperparameter Tuning',
        'dimension_key': 'model_training_and_experimentation',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Search many hyperparameters efficiently.',
        'scenario_context': 'With a large hyperparameter space and limited compute, exhaustive '
                            'grid search is too expensive.',
        'stem': 'Which strategy explores the space more efficiently?',
        'options': [   {'id': 'a', 'label': 'Random search'},
                       {'id': 'b', 'label': 'Full grid search'},
                       {'id': 'c', 'label': 'One fixed setting'},
                       {'id': 'd', 'label': 'Undocumented manual guessing'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Random or Bayesian search finds good configs with fewer trials than '
                       'exhaustive grids.',
        'correct_answer_rationale': 'Random search covers important dimensions better per trial '
                                    'than dense grids.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Random search covers important dimensions '
                                                  'better per trial than dense grids.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Grid search scales combinatorially and wastes '
                                                  'budget.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A single setting performs no search at all.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Undocumented guessing is neither systematic nor '
                                                  'reproducible.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.model_serving.s1.single_choice.batch-vs-online',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'model_serving',
        'competency': 'Model Serving',
        'dimension_key': 'model_deployment_and_serving',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Match serving mode to latency needs.',
        'scenario_context': 'Recommendations must be returned synchronously within a web request.',
        'stem': 'Which serving mode fits this synchronous need?',
        'options': [   {'id': 'a', 'label': 'Online real-time inference'},
                       {'id': 'b', 'label': 'Nightly batch scoring'},
                       {'id': 'c', 'label': 'Manual notebook scoring'},
                       {'id': 'd', 'label': 'Daily emailed predictions'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Real-time request/response needs online serving; batch serving suits '
                       'precomputable predictions.',
        'correct_answer_rationale': 'Online serving returns predictions per request within latency '
                                    'budgets.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Online serving returns predictions per request '
                                                  'within latency budgets.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Batch precomputes offline and cannot answer a '
                                                  'live request freshly.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Notebook scoring is not a production request '
                                                  'path.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Daily email cannot satisfy a synchronous '
                                                  'request.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.model_serving.s1.single_choice.versioning',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'model_serving',
        'competency': 'Model Serving',
        'dimension_key': 'model_deployment_and_serving',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Enable rollbacks with versioning.',
        'scenario_context': 'A newly deployed model degrades metrics, and the team needs to revert '
                            'quickly and compare versions.',
        'stem': 'Which practice makes the rollback safe?',
        'options': [   {'id': 'a', 'label': 'Serve versioned model artifacts'},
                       {'id': 'b', 'label': 'Overwrite the previous model'},
                       {'id': 'c', 'label': 'Hard-code weights in app'},
                       {'id': 'd', 'label': 'Disable monitoring during rollout'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Versioned, immutable artifacts enable instant rollback and A/B comparison, '
                       'a core MLOps practice.',
        'correct_answer_rationale': 'Versioned artifacts let you route to a previous known-good '
                                    'model instantly.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Versioned artifacts let you route to a previous '
                                                  'known-good model instantly.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Overwriting destroys the ability to roll back.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Inlined weights cannot be swapped or versioned '
                                                  'cleanly.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Removing monitoring hides the regression.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.ml_pipelines.s1.single_choice.reproducibility',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'ml_pipelines',
        'competency': 'ML Pipelines',
        'dimension_key': 'mlops_and_pipelines',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Make ML pipelines reproducible.',
        'scenario_context': 'A training result cannot be reproduced because data and code versions '
                            'were not recorded.',
        'stem': 'Which practice most improves reproducibility?',
        'options': [   {'id': 'a', 'label': 'Version data, code, params'},
                       {'id': 'b', 'label': 'Use latest unpinned dependencies'},
                       {'id': 'c', 'label': 'Sample without a seed'},
                       {'id': 'd', 'label': 'Delete intermediate artifacts'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Reproducible pipelines pin and track data, code, parameters, and seeds.',
        'correct_answer_rationale': 'Pinning data, code, and params lets a run be reproduced '
                                    'exactly.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Pinning data, code, and params lets a run be '
                                                  'reproduced exactly.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Floating dependencies make runs '
                                                  'non-deterministic.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Without a seed the sample changes each run.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Discarding artifacts removes the trail to '
                                                  'reproduce.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'machine_learning_engineer.ml_pipelines.s1.single_choice.orchestration',
        'role_key': 'machine_learning_engineer',
        'subskill_key': 'ml_pipelines',
        'competency': 'ML Pipelines',
        'dimension_key': 'mlops_and_pipelines',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Express pipeline steps as a DAG.',
        'scenario_context': 'Ad-hoc scripts run preprocessing, training, and evaluation, but '
                            'failures leave the workflow in an unknown state.',
        'stem': 'Which approach gives ordered steps with retries?',
        'options': [   {'id': 'a', 'label': 'Define steps as a DAG'},
                       {'id': 'b', 'label': 'Chain scripts with sleeps'},
                       {'id': 'c', 'label': 'Run everything in one cell'},
                       {'id': 'd', 'label': 'Trigger each step manually'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Orchestrators model pipelines as DAGs with dependencies, retries, and '
                       'observability.',
        'correct_answer_rationale': 'An orchestrated DAG sequences steps with dependencies, '
                                    'retries, and monitoring.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'An orchestrated DAG sequences steps with '
                                                  'dependencies, retries, and monitoring.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Fixed sleeps are brittle and track no '
                                                  'dependencies.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A monolithic run lacks step isolation and '
                                                  'retries.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Manual triggering gives no automated ordering '
                                                  'or recovery.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'}]
