"""Scenario corpus for ``role_key = "ui_ux_designer"``.

Tier-1 stage-1 calibration content (single_choice, >=2 per calibration
subskill) authored as original internal content and human-reviewed. Identity
and governance fields (competency, dimension_key, doc_id, corpus_version) are
bound to the curated role graph so they cannot drift from the taxonomy.

Author additional scenarios here following ``AUTHOR_GUIDE.md``.
"""

from __future__ import annotations

from apps.assessments.scenario_corpus.schema import ScenarioDocument


SCENARIOS: list[ScenarioDocument] = [   {   'doc_id': 'ui_ux_designer.user_interviews.s1.single_choice.open-question',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'user_interviews',
        'competency': 'User Interviews',
        'dimension_key': 'research_discovery',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Ask non-leading interview questions.',
        'scenario_context': 'A researcher wants honest insight into how users currently solve a '
                            'problem.',
        'stem': 'Which question is the least leading?',
        'options': [   {'id': 'a', 'label': 'Walk me through last time'},
                       {'id': 'b', 'label': "Isn't this feature great"},
                       {'id': 'c', 'label': 'Would you pay more'},
                       {'id': 'd', 'label': 'You like fast apps'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Effective interviews use open, behavior-focused questions about real past '
                       'actions.',
        'correct_answer_rationale': 'An open, past-behavior prompt avoids steering and elicits '
                                    'real detail.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'An open, past-behavior prompt avoids steering '
                                                  'and elicits real detail.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'It pressures the participant toward agreement.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Loaded wording biases the answer.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'A yes-leading question invites acquiescence '
                                                  'bias.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.user_interviews.s1.single_choice.behavior-vs-opinion',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'user_interviews',
        'competency': 'User Interviews',
        'dimension_key': 'research_discovery',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Prioritize behavior over speculation.',
        'scenario_context': 'Participants say they would use a feature daily, but the team wants '
                            'reliable signal about real usage.',
        'stem': 'Which focus yields the most trustworthy signal?',
        'options': [   {'id': 'a', 'label': 'Concrete past behavior'},
                       {'id': 'b', 'label': 'Predicted future usage'},
                       {'id': 'c', 'label': 'Preferred color choice'},
                       {'id': 'd', 'label': 'Rating the team idea'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Grounding interviews in actual past behavior reduces the say-do gap.',
        'correct_answer_rationale': 'Past behavior predicts future behavior better than stated '
                                    'intentions.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Past behavior predicts future behavior better '
                                                  'than stated intentions.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Stated future intent correlates weakly with '
                                                  'real behavior.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Color preference does not address usage.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': "Rating the team's idea invites politeness "
                                                  'bias.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.information_architecture.s1.single_choice.card-sort',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'information_architecture',
        'competency': 'Information Architecture',
        'dimension_key': 'interaction_design',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Validate grouping with users.',
        'scenario_context': 'A team is unsure how users expect content categories to be grouped in '
                            'the menu.',
        'stem': "Which method surfaces users' grouping model?",
        'options': [   {'id': 'a', 'label': 'A card sort'},
                       {'id': 'b', 'label': 'A brand workshop'},
                       {'id': 'c', 'label': 'A pricing survey'},
                       {'id': 'd', 'label': 'A load test'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': "Card sorting elicits users' mental models for grouping and labeling "
                       'content.',
        'correct_answer_rationale': 'Card sorting reveals how users naturally group and label '
                                    'content.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Card sorting reveals how users naturally group '
                                                  'and label content.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Brand work shapes identity, not user grouping.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Pricing is unrelated to navigation structure.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Load testing measures performance, not IA '
                                                  'grouping.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.information_architecture.s1.single_choice.findability',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'information_architecture',
        'competency': 'Information Architecture',
        'dimension_key': 'interaction_design',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Improve findability through hierarchy.',
        'scenario_context': 'Users cannot locate a settings option buried five levels deep in '
                            'unrelated menus.',
        'stem': 'Which change most improves findability?',
        'options': [   {'id': 'a', 'label': 'Group related items shallowly'},
                       {'id': 'b', 'label': 'Add more nesting levels'},
                       {'id': 'c', 'label': 'Hide settings behind gesture'},
                       {'id': 'd', 'label': 'Rename items with jargon'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Findability improves with a logical, shallow hierarchy and clear, expected '
                       'labels.',
        'correct_answer_rationale': 'Logical grouping and shallower depth make items easier to '
                                    'find.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Logical grouping and shallower depth make items '
                                                  'easier to find.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Deeper nesting worsens findability.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Hidden gestures reduce discoverability.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Jargon labels hurt recognition for users.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.visual_hierarchy.s1.single_choice.primary-action',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'visual_hierarchy',
        'competency': 'Visual Hierarchy',
        'dimension_key': 'visual_systems',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Direct attention to the primary action.',
        'scenario_context': 'A form shows Submit and Cancel with identical styling, leaving the '
                            'main action unclear.',
        'stem': 'Which change best signals the primary action?',
        'options': [   {'id': 'a', 'label': 'Emphasize Submit over Cancel'},
                       {'id': 'b', 'label': 'Make both buttons identical'},
                       {'id': 'c', 'label': 'Hide the Cancel button'},
                       {'id': 'd', 'label': 'Shrink both buttons equally'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Visual hierarchy uses contrast, size, and weight to make the primary '
                       'action stand out.',
        'correct_answer_rationale': 'Stronger contrast and weight mark the primary action clearly.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Stronger contrast and weight mark the primary '
                                                  'action clearly.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Equal styling is what hides the primary '
                                                  'action.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Removing Cancel harms usability without '
                                                  'clarifying primacy.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Equal shrinking still leaves no hierarchy.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.visual_hierarchy.s1.single_choice.scan-order',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'visual_hierarchy',
        'competency': 'Visual Hierarchy',
        'dimension_key': 'visual_systems',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Guide the eye with size and contrast.',
        'scenario_context': 'All text on a landing page is the same size, so users cannot tell '
                            'what to read first.',
        'stem': 'Which technique establishes a reading order?',
        'options': [   {'id': 'a', 'label': 'Vary type size and weight'},
                       {'id': 'b', 'label': 'Set everything one size'},
                       {'id': 'c', 'label': 'Use one flat color'},
                       {'id': 'd', 'label': 'Center every text line'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Differences in size, weight, and contrast establish hierarchy and reading '
                       'order.',
        'correct_answer_rationale': 'Differentiated scale and weight create a scannable order of '
                                    'importance.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Differentiated scale and weight create a '
                                                  'scannable order of importance.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Uniform size removes hierarchy entirely.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A single flat treatment gives no emphasis '
                                                  'cues.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Centering alone does not rank importance.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.usability_testing.s1.single_choice.task-based',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'usability_testing',
        'competency': 'Usability Testing',
        'dimension_key': 'validation_delivery',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Run task-based usability tests.',
        'scenario_context': 'A team wants to find where users struggle to complete a checkout.',
        'stem': 'Which session design reveals real problems?',
        'options': [   {'id': 'a', 'label': 'Observe realistic task attempts'},
                       {'id': 'b', 'label': 'Ask only about style'},
                       {'id': 'c', 'label': 'Demo then ask if liked'},
                       {'id': 'd', 'label': 'Survey about other features'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': 'Task-based testing with realistic goals and observation surfaces where '
                       'users actually struggle.',
        'correct_answer_rationale': 'Observing real task attempts exposes actual friction points.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Observing real task attempts exposes actual '
                                                  'friction points.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Aesthetic ratings miss task friction.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'A guided demo hides where users would struggle '
                                                  'alone.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'Off-task surveys do not reveal checkout '
                                                  'problems.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'},
    {   'doc_id': 'ui_ux_designer.usability_testing.s1.single_choice.think-aloud',
        'role_key': 'ui_ux_designer',
        'subskill_key': 'usability_testing',
        'competency': 'Usability Testing',
        'dimension_key': 'validation_delivery',
        'stage': 1,
        'question_type': 'single_choice',
        'difficulty': 3,
        'estimated_seconds': 55,
        'learning_objective': 'Capture reasoning with think-aloud.',
        'scenario_context': 'Observers can see that users hesitate but not why they get confused.',
        'stem': 'Which technique reveals the reasoning behind it?',
        'options': [   {'id': 'a', 'label': 'Ask participants to think aloud'},
                       {'id': 'b', 'label': 'Mute participants during tasks'},
                       {'id': 'c', 'label': 'Record only completion time'},
                       {'id': 'd', 'label': 'Replace it with polling'}],
        'answer_key': {'correct_option_ids': ['a'], 'scoring': 'single_best'},
        'explanation': "The think-aloud protocol captures users' moment-to-moment reasoning behind "
                       'observed hesitation.',
        'correct_answer_rationale': 'Think-aloud narration exposes the reasoning behind actions '
                                    'and confusion.',
        'option_rationales': [   {   'option_id': 'a',
                                     'is_correct': True,
                                     'rationale': 'Think-aloud narration exposes the reasoning '
                                                  'behind actions and confusion.'},
                                 {   'option_id': 'b',
                                     'is_correct': False,
                                     'rationale': 'Silence hides exactly the reasoning you need.'},
                                 {   'option_id': 'c',
                                     'is_correct': False,
                                     'rationale': 'Time shows that they struggled, not why.'},
                                 {   'option_id': 'd',
                                     'is_correct': False,
                                     'rationale': 'A poll does not reveal individual reasoning.'}],
        'author': 'internal-authored-tier1',
        'license': 'internal-original-content',
        'review_status': 'approved',
        'created_at': '2026-06-20',
        'corpus_version': 'scenario-v1'}]
