# Generated by Django 5.0 on 2025-12-26 21:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Conversation title (auto-generated from first message)",
                        max_length=255,
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("general", "General Career Questions"),
                            ("roadmap", "Roadmap Guidance"),
                            ("assessment", "Assessment Interpretation"),
                            ("job_search", "Job Search Assistance"),
                            ("career_advice", "Career Advisory"),
                        ],
                        default="general",
                        help_text="Primary topic of conversation",
                        max_length=100,
                    ),
                ),
                (
                    "context_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of user context at conversation start",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this conversation is currently active",
                    ),
                ),
                (
                    "last_message_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last message in conversation",
                        null=True,
                    ),
                ),
                (
                    "message_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of messages in conversation"
                    ),
                ),
                (
                    "total_tokens_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total LLM tokens consumed in this conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who initiated this conversation",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "ordering": ["-last_message_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User Message"),
                            ("assistant", "AI Assistant"),
                            ("system", "System Message"),
                        ],
                        help_text="Who sent this message",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Message content (user input or AI response)"
                    ),
                ),
                (
                    "context_used",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="RAG context retrieved and used for generating this response",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True,
                        help_text="LLM model used for this response (e.g., 'gpt-4', 'claude-3-sonnet')",
                        max_length=100,
                    ),
                ),
                (
                    "tokens_used",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of tokens consumed for this message",
                        null=True,
                    ),
                ),
                (
                    "response_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Time taken to generate response (milliseconds)",
                        null=True,
                    ),
                ),
                (
                    "user_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="User rating of AI response (1-5 stars)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether user found this response helpful",
                        null=True,
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(
                        blank=True, help_text="Optional user feedback text"
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        help_text="Conversation this message belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="advisory.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-last_message_at"], name="idx_conv_user_last_msg"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["is_active"], name="idx_conv_active"),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(fields=["topic"], name="idx_conv_topic"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"], name="idx_msg_conv_created"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["role"], name="idx_msg_role"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["created_at"], name="idx_msg_created"),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(fields=["model_used"], name="idx_msg_model"),
        ),
    ]
