# Generated by Django 5.0 on 2026-01-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advisory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error details if processing failed"
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("completed", "Completed"),
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("failed", "Failed"),
                ],
                default="completed",
                help_text="Status of AI message processing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="task_id",
            field=models.CharField(
                blank=True,
                help_text="Celery task ID for async processing",
                max_length=255,
            ),
        ),
    ]
