from __future__ import annotations

from apps.assessments.role_graph import CoreDimension, RoleGraph, SubSkill


CURATED_VERSION = "curated-v1"


def skill(
    key: str,
    label: str,
    dimension: str,
    target_proficiency: int,
    prerequisites: list[str] | None = None,
) -> SubSkill:
    return SubSkill(
        key=key,
        label=label,
        dimension=dimension,
        target_proficiency=target_proficiency,
        prerequisites=prerequisites or [],
    )


def dimension(
    key: str,
    label: str,
    weight: float,
    subskills: list[SubSkill],
) -> CoreDimension:
    return CoreDimension(
        key=key,
        label=label,
        weight=weight,
        subskills=subskills,
    )


ROLE_GRAPHS = {
    "backend": RoleGraph(
        role_key="backend",
        role_label="Backend Developer",
        version=CURATED_VERSION,
        dimensions=[
            dimension(
                "api_service_design",
                "API and Service Design",
                0.30,
                [
                    skill("http_api_design", "HTTP API Design", "api_service_design", 4),
                    skill(
                        "service_decomposition",
                        "Service Decomposition",
                        "api_service_design",
                        4,
                        ["http_api_design"],
                    ),
                    skill(
                        "auth_authorization",
                        "Authentication and Authorization",
                        "api_service_design",
                        4,
                        ["http_api_design"],
                    ),
                    skill(
                        "async_workflows",
                        "Asynchronous Workflows",
                        "api_service_design",
                        3,
                        ["service_decomposition"],
                    ),
                ],
            ),
            dimension(
                "data_persistence",
                "Data Modeling and Persistence",
                0.25,
                [
                    skill("relational_modeling", "Relational Modeling", "data_persistence", 4),
                    skill(
                        "query_optimization",
                        "Query Optimization",
                        "data_persistence",
                        4,
                        ["relational_modeling"],
                    ),
                    skill(
                        "schema_migrations",
                        "Schema Migrations",
                        "data_persistence",
                        4,
                        ["relational_modeling"],
                    ),
                    skill(
                        "caching_patterns",
                        "Caching Patterns",
                        "data_persistence",
                        3,
                        ["query_optimization"],
                    ),
                ],
            ),
            dimension(
                "reliability_operations",
                "Reliability and Operations",
                0.25,
                [
                    skill("logging_monitoring", "Logging and Monitoring", "reliability_operations", 4),
                    skill(
                        "backend_testing_strategy",
                        "Backend Testing Strategy",
                        "reliability_operations",
                        4,
                        ["http_api_design"],
                    ),
                    skill(
                        "performance_debugging",
                        "Performance Debugging",
                        "reliability_operations",
                        4,
                        ["logging_monitoring"],
                    ),
                    skill(
                        "deployment_readiness",
                        "Deployment Readiness",
                        "reliability_operations",
                        3,
                        ["backend_testing_strategy"],
                    ),
                ],
            ),
            dimension(
                "delivery_collaboration",
                "Delivery and Collaboration",
                0.20,
                [
                    skill(
                        "requirement_translation",
                        "Requirement Translation",
                        "delivery_collaboration",
                        4,
                    ),
                    skill("code_review_practice", "Code Review Practice", "delivery_collaboration", 3),
                    skill(
                        "technical_documentation",
                        "Technical Documentation",
                        "delivery_collaboration",
                        3,
                        ["requirement_translation"],
                    ),
                    skill(
                        "delivery_planning",
                        "Delivery Planning",
                        "delivery_collaboration",
                        3,
                        ["requirement_translation"],
                    ),
                ],
            ),
        ],
    ),
    "frontend": RoleGraph(
        role_key="frontend",
        role_label="Frontend Developer",
        version=CURATED_VERSION,
        dimensions=[
            dimension(
                "interface_foundations",
                "Interface Foundations",
                0.30,
                [
                    skill("semantic_html", "Semantic HTML", "interface_foundations", 4),
                    skill(
                        "responsive_css",
                        "Responsive CSS",
                        "interface_foundations",
                        4,
                        ["semantic_html"],
                    ),
                    skill(
                        "accessibility_fundamentals",
                        "Accessibility Fundamentals",
                        "interface_foundations",
                        4,
                        ["semantic_html"],
                    ),
                    skill("ui_state_basics", "UI State Basics", "interface_foundations", 4),
                ],
            ),
            dimension(
                "component_architecture",
                "Component Architecture",
                0.25,
                [
                    skill(
                        "component_composition",
                        "Component Composition",
                        "component_architecture",
                        4,
                        ["ui_state_basics"],
                    ),
                    skill(
                        "typescript_frontend",
                        "TypeScript for Frontend",
                        "component_architecture",
                        4,
                        ["component_composition"],
                    ),
                    skill(
                        "async_data_fetching",
                        "Asynchronous Data Fetching",
                        "component_architecture",
                        4,
                        ["component_composition"],
                    ),
                    skill(
                        "routing_navigation",
                        "Routing and Navigation",
                        "component_architecture",
                        3,
                        ["component_composition"],
                    ),
                ],
            ),
            dimension(
                "quality_performance",
                "Quality and Performance",
                0.25,
                [
                    skill("browser_debugging", "Browser Debugging", "quality_performance", 4),
                    skill(
                        "frontend_testing",
                        "Frontend Testing",
                        "quality_performance",
                        4,
                        ["component_composition"],
                    ),
                    skill(
                        "rendering_performance",
                        "Rendering Performance",
                        "quality_performance",
                        3,
                        ["browser_debugging"],
                    ),
                    skill(
                        "form_validation_flows",
                        "Form and Validation Flows",
                        "quality_performance",
                        3,
                        ["ui_state_basics"],
                    ),
                ],
            ),
            dimension(
                "product_delivery",
                "Product Delivery",
                0.20,
                [
                    skill("design_translation", "Design Translation", "product_delivery", 4),
                    skill(
                        "api_integration",
                        "API Integration",
                        "product_delivery",
                        4,
                        ["async_data_fetching"],
                    ),
                    skill(
                        "design_system_usage",
                        "Design System Usage",
                        "product_delivery",
                        3,
                        ["design_translation"],
                    ),
                    skill(
                        "cross_functional_alignment",
                        "Cross-functional Alignment",
                        "product_delivery",
                        3,
                        ["design_translation"],
                    ),
                ],
            ),
        ],
    ),
    "data_science": RoleGraph(
        role_key="data_science",
        role_label="Data Scientist",
        version=CURATED_VERSION,
        dimensions=[
            dimension(
                "data_preparation",
                "Data Preparation",
                0.30,
                [
                    skill("python_data_analysis", "Python Data Analysis", "data_preparation", 4),
                    skill("sql_analysis", "SQL Analysis", "data_preparation", 4),
                    skill(
                        "data_cleaning",
                        "Data Cleaning",
                        "data_preparation",
                        4,
                        ["python_data_analysis"],
                    ),
                    skill(
                        "exploratory_analysis",
                        "Exploratory Analysis",
                        "data_preparation",
                        4,
                        ["data_cleaning"],
                    ),
                ],
            ),
            dimension(
                "statistics_experimentation",
                "Statistics and Experimentation",
                0.25,
                [
                    skill(
                        "statistical_reasoning",
                        "Statistical Reasoning",
                        "statistics_experimentation",
                        4,
                    ),
                    skill(
                        "hypothesis_testing",
                        "Hypothesis Testing",
                        "statistics_experimentation",
                        4,
                        ["statistical_reasoning"],
                    ),
                    skill(
                        "feature_engineering",
                        "Feature Engineering",
                        "statistics_experimentation",
                        4,
                        ["exploratory_analysis"],
                    ),
                    skill(
                        "experiment_design",
                        "Experiment Design",
                        "statistics_experimentation",
                        3,
                        ["hypothesis_testing"],
                    ),
                ],
            ),
            dimension(
                "modeling_evaluation",
                "Modeling and Evaluation",
                0.25,
                [
                    skill(
                        "supervised_modeling",
                        "Supervised Modeling",
                        "modeling_evaluation",
                        4,
                        ["feature_engineering"],
                    ),
                    skill(
                        "model_validation",
                        "Model Validation",
                        "modeling_evaluation",
                        4,
                        ["supervised_modeling"],
                    ),
                    skill(
                        "error_analysis",
                        "Error Analysis",
                        "modeling_evaluation",
                        4,
                        ["model_validation"],
                    ),
                    skill(
                        "experiment_tracking",
                        "Experiment Tracking",
                        "modeling_evaluation",
                        3,
                        ["supervised_modeling"],
                    ),
                ],
            ),
            dimension(
                "communication_delivery",
                "Communication and Delivery",
                0.20,
                [
                    skill(
                        "data_storytelling",
                        "Data Storytelling",
                        "communication_delivery",
                        4,
                        ["exploratory_analysis"],
                    ),
                    skill(
                        "stakeholder_reporting",
                        "Stakeholder Reporting",
                        "communication_delivery",
                        3,
                        ["data_storytelling"],
                    ),
                    skill(
                        "notebook_reproducibility",
                        "Notebook Reproducibility",
                        "communication_delivery",
                        3,
                        ["python_data_analysis"],
                    ),
                    skill(
                        "ml_handoff_readiness",
                        "ML Handoff Readiness",
                        "communication_delivery",
                        3,
                        ["experiment_tracking"],
                    ),
                ],
            ),
        ],
    ),
    "fullstack": RoleGraph(
        role_key="fullstack",
        role_label="Full Stack Developer",
        version=CURATED_VERSION,
        dimensions=[
            dimension(
                "product_interface",
                "Product Interface Work",
                0.30,
                [
                    skill("ui_implementation", "UI Implementation", "product_interface", 4),
                    skill(
                        "frontend_state_management",
                        "Frontend State Management",
                        "product_interface",
                        4,
                        ["ui_implementation"],
                    ),
                    skill(
                        "form_validation_flows",
                        "Form and Validation Flows",
                        "product_interface",
                        4,
                        ["ui_implementation"],
                    ),
                    skill(
                        "client_routing",
                        "Client Routing",
                        "product_interface",
                        3,
                        ["ui_implementation"],
                    ),
                ],
            ),
            dimension(
                "api_service_layer",
                "API and Service Layer",
                0.25,
                [
                    skill("api_delivery", "API Delivery", "api_service_layer", 4),
                    skill(
                        "authentication_flows",
                        "Authentication Flows",
                        "api_service_layer",
                        4,
                        ["api_delivery"],
                    ),
                    skill(
                        "service_integration",
                        "Service Integration",
                        "api_service_layer",
                        4,
                        ["api_delivery"],
                    ),
                    skill(
                        "background_jobs",
                        "Background Jobs",
                        "api_service_layer",
                        3,
                        ["service_integration"],
                    ),
                ],
            ),
            dimension(
                "data_integration",
                "Data and Integration",
                0.25,
                [
                    skill("relational_modeling", "Relational Modeling", "data_integration", 4),
                    skill(
                        "end_to_end_data_flow",
                        "End-to-end Data Flow",
                        "data_integration",
                        4,
                        ["ui_implementation", "api_delivery"],
                    ),
                    skill(
                        "caching_and_session_state",
                        "Caching and Session State",
                        "data_integration",
                        3,
                        ["authentication_flows"],
                    ),
                    skill(
                        "debugging_across_layers",
                        "Debugging Across Layers",
                        "data_integration",
                        4,
                        ["end_to_end_data_flow"],
                    ),
                ],
            ),
            dimension(
                "delivery_ownership",
                "Delivery Ownership",
                0.20,
                [
                    skill("product_slicing", "Product Slicing", "delivery_ownership", 4),
                    skill(
                        "testing_strategy",
                        "Testing Strategy",
                        "delivery_ownership",
                        4,
                        ["debugging_across_layers"],
                    ),
                    skill(
                        "deployment_pipeline",
                        "Deployment Pipeline",
                        "delivery_ownership",
                        3,
                        ["service_integration"],
                    ),
                    skill(
                        "technical_handoff",
                        "Technical Handoff",
                        "delivery_ownership",
                        3,
                        ["product_slicing"],
                    ),
                ],
            ),
        ],
    ),
    "mobile": RoleGraph(
        role_key="mobile",
        role_label="Mobile Developer",
        version=CURATED_VERSION,
        dimensions=[
            dimension(
                "app_foundations",
                "App Foundations",
                0.30,
                [
                    skill("mobile_ui_layouts", "Mobile UI Layouts", "app_foundations", 4),
                    skill(
                        "navigation_flows",
                        "Navigation Flows",
                        "app_foundations",
                        4,
                        ["mobile_ui_layouts"],
                    ),
                    skill(
                        "local_state_management",
                        "Local State Management",
                        "app_foundations",
                        4,
                        ["mobile_ui_layouts"],
                    ),
                    skill(
                        "platform_accessibility",
                        "Platform Accessibility",
                        "app_foundations",
                        3,
                        ["mobile_ui_layouts"],
                    ),
                ],
            ),
            dimension(
                "data_integration",
                "Data and Integration",
                0.25,
                [
                    skill("api_consumption", "API Consumption", "data_integration", 4),
                    skill(
                        "local_persistence",
                        "Local Persistence",
                        "data_integration",
                        4,
                        ["api_consumption"],
                    ),
                    skill(
                        "async_state_handling",
                        "Asynchronous State Handling",
                        "data_integration",
                        4,
                        ["local_state_management"],
                    ),
                    skill(
                        "offline_sync_patterns",
                        "Offline Sync Patterns",
                        "data_integration",
                        3,
                        ["local_persistence"],
                    ),
                ],
            ),
            dimension(
                "native_capabilities",
                "Native Capabilities",
                0.25,
                [
                    skill("device_permissions", "Device Permissions", "native_capabilities", 3),
                    skill(
                        "notifications_integration",
                        "Notifications Integration",
                        "native_capabilities",
                        3,
                        ["device_permissions"],
                    ),
                    skill(
                        "camera_location_media",
                        "Camera, Location, and Media",
                        "native_capabilities",
                        3,
                        ["device_permissions"],
                    ),
                    skill(
                        "crash_debugging",
                        "Crash Debugging",
                        "native_capabilities",
                        4,
                        ["device_permissions"],
                    ),
                ],
            ),
            dimension(
                "quality_release",
                "Quality and Release",
                0.20,
                [
                    skill(
                        "mobile_testing",
                        "Mobile Testing",
                        "quality_release",
                        4,
                        ["local_state_management"],
                    ),
                    skill(
                        "performance_profiling",
                        "Performance Profiling",
                        "quality_release",
                        3,
                        ["crash_debugging"],
                    ),
                    skill(
                        "store_release_readiness",
                        "Store Release Readiness",
                        "quality_release",
                        3,
                        ["mobile_testing"],
                    ),
                    skill(
                        "analytics_monitoring",
                        "Analytics and Monitoring",
                        "quality_release",
                        3,
                        ["notifications_integration"],
                    ),
                ],
            ),
        ],
    ),
    "devops": RoleGraph(
        role_key="devops",
        role_label="DevOps Engineer",
        version=CURATED_VERSION,
        dimensions=[
            dimension(
                "systems_foundations",
                "Systems Foundations",
                0.30,
                [
                    skill("linux_operations", "Linux Operations", "systems_foundations", 4),
                    skill(
                        "networking_basics",
                        "Networking Basics",
                        "systems_foundations",
                        4,
                        ["linux_operations"],
                    ),
                    skill(
                        "container_fundamentals",
                        "Container Fundamentals",
                        "systems_foundations",
                        4,
                        ["linux_operations"],
                    ),
                    skill(
                        "cloud_compute_basics",
                        "Cloud Compute Basics",
                        "systems_foundations",
                        3,
                        ["networking_basics"],
                    ),
                ],
            ),
            dimension(
                "automation_iac",
                "Automation and Infrastructure as Code",
                0.25,
                [
                    skill(
                        "ci_cd_pipelines",
                        "CI/CD Pipelines",
                        "automation_iac",
                        4,
                        ["container_fundamentals"],
                    ),
                    skill(
                        "infrastructure_as_code",
                        "Infrastructure as Code",
                        "automation_iac",
                        4,
                        ["cloud_compute_basics"],
                    ),
                    skill(
                        "configuration_management",
                        "Configuration Management",
                        "automation_iac",
                        3,
                        ["linux_operations"],
                    ),
                    skill(
                        "artifact_release_management",
                        "Artifact Release Management",
                        "automation_iac",
                        3,
                        ["ci_cd_pipelines"],
                    ),
                ],
            ),
            dimension(
                "observability_reliability",
                "Observability and Reliability",
                0.25,
                [
                    skill(
                        "logging_and_metrics",
                        "Logging and Metrics",
                        "observability_reliability",
                        4,
                    ),
                    skill(
                        "alerting_and_slos",
                        "Alerting and SLOs",
                        "observability_reliability",
                        4,
                        ["logging_and_metrics"],
                    ),
                    skill(
                        "incident_response",
                        "Incident Response",
                        "observability_reliability",
                        4,
                        ["alerting_and_slos"],
                    ),
                    skill(
                        "capacity_performance_analysis",
                        "Capacity and Performance Analysis",
                        "observability_reliability",
                        3,
                        ["logging_and_metrics"],
                    ),
                ],
            ),
            dimension(
                "security_collaboration",
                "Security and Collaboration",
                0.20,
                [
                    skill(
                        "secrets_management",
                        "Secrets Management",
                        "security_collaboration",
                        4,
                        ["infrastructure_as_code"],
                    ),
                    skill(
                        "access_control",
                        "Access Control",
                        "security_collaboration",
                        4,
                        ["cloud_compute_basics"],
                    ),
                    skill(
                        "change_review_practices",
                        "Change Review Practices",
                        "security_collaboration",
                        3,
                        ["ci_cd_pipelines"],
                    ),
                    skill(
                        "platform_documentation",
                        "Platform Documentation",
                        "security_collaboration",
                        3,
                        ["change_review_practices"],
                    ),
                ],
            ),
        ],
    ),
}
