"""Score reference answers for the expert-review packet (keyword/LLM per settings)."""

from __future__ import annotations

import json
from pathlib import Path

from django.core.management.base import BaseCommand

from apps.assessments.engine import AnswerScorer

DEFAULT_ITEMS = (
    Path(__file__).resolve().parents[5]
    / "docs"
    / "product"
    / "expert_review_items.json"
)
DEFAULT_OUTPUT = (
    Path(__file__).resolve().parents[5]
    / "docs"
    / "product"
    / "expert_review_engine_scores.json"
)


class Command(BaseCommand):
    help = "Score expert_review_items.json sample answers and write engine reference scores."

    def add_arguments(self, parser):
        parser.add_argument(
            "--items",
            type=Path,
            default=DEFAULT_ITEMS,
            help="Path to expert_review_items.json",
        )
        parser.add_argument(
            "--output",
            type=Path,
            default=DEFAULT_OUTPUT,
            help="Output JSON mapping item_id -> engine score",
        )

    def handle(self, *args, **options):
        items_path: Path = options["items"]
        output_path: Path = options["output"]
        items = json.loads(items_path.read_text(encoding="utf-8"))

        scores: dict[str, dict[str, object]] = {}
        for item in items:
            item_id = str(item["id"])
            question = {
                "question_type": "open_ended",
                "question_text": item["question_text"],
                "answer_key": item.get("answer_key", {}),
            }
            score, confidence, method = AnswerScorer.score_open_ended(
                question, item["sample_answer"]
            )
            scores[item_id] = {
                "score": round(float(score), 2),
                "confidence": round(float(confidence), 2),
                "scoring_method": method,
            }
            self.stdout.write(f"{item_id}: {score} ({method})")

        payload = {
            "_note": "Generated by manage.py score_expert_review_reference — organizer reference only.",
            "_source_items": str(items_path.relative_to(items_path.parents[2])),
            "scores": scores,
        }
        output_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {output_path}"))
